### ISSUE TITLE
java.util.NoSuchElementException: Collection contains no element matching the predicate.

### ISSUE THREAD

**Issue by renkchina** [ssseasonnn/RxDownload#127]
android studio 3.0
implementation 'zlc.season:rxdownload3:1.1.8'

java.util.NoSuchElementException: Collection contains no element matching the predicate.
                                                                         at zlc.season.rxdownload3.core.RealMission.findExtension(RealMission.kt:300)
                                                                         at zlc.season.rxdownload3.core.LocalMissionBox.extension(LocalMissionBox.kt:116)
                                                                         at zlc.season.rxdownload3.core.DownloadCore.extension(DownloadCore.kt:71)
                                                                         at zlc.season.rxdownload3.RxDownload.extension(RxDownload.kt:100)
                                                                         at zlc.season.rxdownload3.RxDownload.extension(RxDownload.kt:96)

**Comment by ssseasonnn** [comment]
你没有添加extension就调用了
