### ISSUE TITLE
master 分支 点击下载就失败

### ISSUE THREAD

**Issue by zhangwenhao2013** [ssseasonnn/RxDownload#129]
`E/RxDownload: Mission error! recvfrom failed: ECONNRESET (Connection reset by peer)
                                                                             java.net.SocketException: recvfrom failed: ECONNRESET (Connection reset by peer)
                                                                                 at libcore.io.IoBridge.maybeThrowAfterRecvfrom(IoBridge.java:588)
                                                                                 at libcore.io.IoBridge.recvfrom(IoBridge.java:552)
                                                                                 at java.net.PlainSocketImpl.read(PlainSocketImpl.java:481)
                                                                                 at java.net.PlainSocketImpl.-wrap0(PlainSocketImpl.java)
                                                                                 at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237)
                                                                                 at okio.Okio$2.read(Okio.java:139)
                                                                                 at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
                                                                                 at okio.RealBufferedSource.indexOf(RealBufferedSource.java:345)
                                                                                 at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:217)
                                                                                 at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:211)
                                                                                 at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:187)
                                                                                 at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88)
                                                                                 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
                                                                                 at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
                                                                                 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
                                                                                 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
                                                                                 at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
                                                                                 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
                                                                                 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
                                                                                 at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
                                                                                 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
                                                                                 at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
                                                                                 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
                                                                                 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
                                                                                 at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
                                                                                 at okhttp3.RealCall.execute(RealCall.java:77)
                                                                                 at retrofit2.OkHttpCall.execute(OkHttpCall.java:180)
                                                                                 at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:41)
                                                                                 at io.reactivex.Observable.subscribe(Observable.java:10842)
                                                                                 at io.reactivex.internal.operators.observable.ObservableSingleMaybe.subscribeActual(ObservableSingleMaybe.java:30)
                                                                                 at io.reactivex.Maybe.subscribe(Maybe.java:3725)
                                                                                 at io.reactivex.internal.operators.maybe.MaybeFlatten.subscribeActual(MaybeFlatten.java:42)
                                                                                 at io.reactivex.Maybe.subscribe(Maybe.java:3725)
                                                                                 at io.reactivex.internal.operators.maybe.MaybeToFlowable.subscribeActual(MaybeToFlowable.java:45)
                                                                                 at io.reactivex.Flowable.subscribe(Flowable.java:12986)
                                                                                 at io.reactivex.internal.operators.flowable.FlowableFlatMap.subscribeActual(FlowableFlatMap.java:53)
                                                                                 at io.reactivex.Flowable.subscribe(Flowable.java:12986)
                                                                                 at io.reactivex.Flowable.subscribe(Flowable.java:12932)
                                                                                 at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.onNext(FlowableFlatMap.java:163)
                                                                                 at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.onNext(FlowableSubscribeOn.java:97)
                                                                                 at io.reactivex.internal.operators.flowable.FlowableDoOnLifecycle$SubscriptionLambdaSubscriber.onNext(FlowableDoOnLifecycle.java:79)
                                                                                 at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.onNext(FlowableSubscribeOn.java:97)
                                                                                 at io.reactivex.internal.subscriptions.ScalarSubscription.request(ScalarSubscription.java:55)
                                                                                 at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.requestUpstream(FlowableSubscribeOn.java:133)
                                                                                 at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.onSubscribe(FlowableSubscribeOn.java:90)
                                                                                 at io.reactivex.internal.operators.flowable.FlowableJust.subscribeActual(FlowableJust.java:34)
                                                                                 at io.reactivex.Flowable.subscribe(Flowable.java:12986)
                                                                                 at io.reactivex.Flowable.subscribe(Flowable.java:12932)
                                                                             	at io.re
11-20 14:35:31.856 13675-18032/zlc.season.rxdownload.java_demo D/RxDownload: Mission finally!`

**Comment by zhangwenhao2013** [comment]
地址失效  更新下地址就ok了
