### ISSUE TITLE
download error while the file left above 90%,alaways

### ISSUE THREAD

**Issue by TristanLudrow** [ssseasonnn/RxDownload#132]
# when download 90% or so, status to be Failed and throw this Exception:

```
11-21 21:01:52.885 4451-4495/com.ynrcc.store E/RxDownload: Mission error! 4 exceptions occurred. 
                                                           io.reactivex.exceptions.CompositeException: 4 exceptions occurred. 
                                                               at io.reactivex.internal.util.ExceptionHelper.addThrowable(ExceptionHelper.java:66)
                                                               at io.reactivex.internal.util.AtomicThrowable.addThrowable(AtomicThrowable.java:35)
                                                               at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.innerError(FlowableFlatMap.java:594)
                                                               at io.reactivex.internal.operators.flowable.FlowableFlatMap$InnerSubscriber.onError(FlowableFlatMap.java:665)
                                                               at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.checkTerminate(FlowableFlatMap.java:563)
                                                               at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.drainLoop(FlowableFlatMap.java:374)
                                                               at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.drain(FlowableFlatMap.java:366)
                                                               at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.innerError(FlowableFlatMap.java:602)
                                                               at io.reactivex.internal.operators.flowable.FlowableFlatMap$InnerSubscriber.onError(FlowableFlatMap.java:665)
                                                               at io.reactivex.subscribers.SerializedSubscriber.onError(SerializedSubscriber.java:142)
                                                               at io.reactivex.internal.operators.flowable.FlowableSampleTimed$SampleTimedSubscriber.onError(FlowableSampleTimed.java:93)
                                                               at io.reactivex.internal.operators.flowable.FlowableCreate$BaseEmitter.onError(FlowableCreate.java:268)
                                                               at io.reactivex.internal.operators.flowable.FlowableCreate$BufferAsyncEmitter.drain(FlowableCreate.java:510)
                                                               at io.reactivex.internal.operators.flowable.FlowableCreate$BufferAsyncEmitter.onError(FlowableCreate.java:461)
                                                               at io.reactivex.internal.operators.flowable.FlowableCreate.subscribeActual(FlowableCreate.java:75)
                                                               at io.reactivex.Flowable.subscribe(Flowable.java:12986)
                                                               at io.reactivex.internal.operators.flowable.FlowableSampleTimed.subscribeActual(FlowableSampleTimed.java:47)
                                                               at io.reactivex.Flowable.subscribe(Flowable.java:12986)
                                                               at io.reactivex.Flowable.subscribe(Flowable.java:12932)
                                                               at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.onNext(FlowableFlatMap.java:163)
                                                               at io.reactivex.internal.subscriptions.DeferredScalarSubscription.complete(DeferredScalarSubscription.java:133)
                                                               at io.reactivex.internal.operators.maybe.MaybeToFlowable$MaybeToFlowableSubscriber.onSuccess(MaybeToFlowable.java:70)
                                                               at io.reactivex.internal.operators.maybe.MaybeFlatten$FlatMapMaybeObserver$InnerObserver.onSuccess(MaybeFlatten.java:120)
                                                               at io.reactivex.internal.operators.maybe.MaybePeek$MaybePeekObserver.onSuccess(MaybePeek.java:122)
                                                               at io.reactivex.internal.operators.observable.ObservableSingleMaybe$SingleElementObserver.onComplete(ObservableSingleMaybe.java:101)
                                                               at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:47)
                                                               at io.reactivex.Observable.subscribe(Observable.java:10842)
                                                               at io.reactivex.internal.operators.observable.ObservableSingleMaybe.subscribeActual(ObservableSingleMaybe.java:30)
                                                               at io.reactivex.Maybe.subscribe(Maybe.java:3725)
                                                               at io.reactivex.internal.operators.maybe.MaybePeek.subscribeActual(MaybePeek.java:56)
                                                               at io.reactivex.Maybe.subscribe(Maybe.java:3725)
                                                               at io.reactivex.internal.operators.maybe.MaybeFlatten$FlatMapMaybeObserver.onSuccess(MaybeFlatten.java:97)
                                                               at io.reactivex.internal.operators.maybe.MaybePeek$MaybePeekObserver.onSuccess(MaybePeek.java:122)
                                                               at io.reactivex.internal.operators.maybe.MaybeMap$MapMaybeObserver.onSuccess(MaybeMap.java:89)
                                                               at io.reactivex.internal.operators.maybe.MaybeSubscribeOn$SubscribeOnMaybeObserver.onSuccess(MaybeSubscribeOn.java:91)
                                                               at io.reactivex.internal.operators.maybe.MaybeJust.subscribeActual(MaybeJust.java:36)
                                                               at io.reactivex.Maybe.subscribe(Maybe.java:3725)
                                                               at io.reactivex.internal.operators.maybe.MaybeSubscribeOn$SubscribeTask.run(MaybeSubscribeOn.java:54)
                                                               at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:452)
                                                               at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
                                                               at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
                                                           	at java.util
```
# then i try to redownload and completed.but i get an  parse apk file error when install the apk.
I guess the three thread to merge the byte array error ,but your demo is ok.....can you help me? is my code error or init wrong?
![image](https://user-images.githubusercontent.com/16358265/33074311-a708d1b6-cf00-11e7-98f5-c84e360468a2.png)

**Comment by ssseasonnn** [comment]
你代码怎么写的？

**Comment by ssseasonnn** [comment]
你试下把链接放到demo里去运行一下试下
