### ISSUE TITLE
下载时候，下载文件到70%的时候就会报错误

### ISSUE THREAD

**Issue by mmengchen** [ssseasonnn/RxDownload#139]
下载时候，下载文件到70%的时候就会报错误，以下是错误
`Mission error! 21 exceptions occurred. 
                                                            io.reactivex.exceptions.CompositeException: 21 exceptions occurred. 
                                                                at io.reactivex.internal.util.ExceptionHelper.addThrowable(ExceptionHelper.java:66)
                                                                at io.reactivex.internal.util.AtomicThrowable.addThrowable(AtomicThrowable.java:35)
                                                                at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.innerError(FlowableFlatMap.java:594)
                                                                at io.reactivex.internal.operators.flowable.FlowableFlatMap$InnerSubscriber.onError(FlowableFlatMap.java:665)
                                                                at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.checkTerminate(FlowableFlatMap.java:563)
                                                                at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.drainLoop(FlowableFlatMap.java:374)
                                                                at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.drain(FlowableFlatMap.java:366)
                                                                at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.innerError(FlowableFlatMap.java:602)
                                                                at io.reactivex.internal.operators.flowable.FlowableFlatMap$InnerSubscriber.onError(FlowableFlatMap.java:665)
                                                                at io.reactivex.subscribers.SerializedSubscriber.onError(SerializedSubscriber.java:142)
                                                                at io.reactivex.internal.operators.flowable.FlowableSampleTimed$SampleTimedSubscriber.emit(FlowableSampleTimed.java:128)
                                                                at io.reactivex.internal.operators.flowable.FlowableSampleTimed$SampleTimedEmitLast.run(FlowableSampleTimed.java:177)
                                                                at io.reactivex.internal.schedulers.ScheduledDirectPeriodicTask.run(ScheduledDirectPeriodicTask.java:39)
                                                                at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:278)
                                                                at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:270)
                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                at java.lang.Thread.run(Thread.java:818)
                                                              ComposedException 1 :
                                                            	io.reactivex.exceptions.MissingBackpressureException: Couldn't emit value due to lack of requests!
                                                                at io.reactivex.internal.operators.flowable.FlowableSampleTimed$SampleTimedSubscriber.emit(FlowableSampleTimed.java:128)
                                                                at io.reactivex.internal.operators.flowable.FlowableSampleTimed$SampleTimedEmitLast.run(FlowableSampleTimed.java:177)
                                                                at io.reactivex.internal.schedulers.ScheduledDirectPeriodicTask.run(ScheduledDirectPeriodicTask.java:39)
                                                                at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:278)
                                                                at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:270)
                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                at java.lang.Thread.run(Thread.java:818)
                                                             Caused by: io.reactivex.exceptions.MissingBackpressureException: Couldn't emit value due to lack of requests!
                                                                at io.reactivex.internal.operators.flowable.FlowableSampleTimed$SampleTimedSubscriber.emit(FlowableSampleTimed.java:128)
                                                                at io.reactivex.internal.operators.flowable.FlowableSampleTimed$SampleTimedEmitLast.run(FlowableSampleTimed.java:177)
                                                                at io.reactivex.internal.schedulers.ScheduledDirectPeriodicTask.run(ScheduledDirectPeriodicTask.java:39)
                                                                at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:278)
                                                                at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:270)
                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                at java.lang.Thread.run(Thread.java:818)
                                                             Caused by: io.reactivex.exceptions.MissingBackpressureException: Couldn't emit value due to lack of requests!
                                                            		at io.reactivex.internal.operators.flowable.FlowableSampleTimed$SampleTimedSubscriber.em`

**Comment by JasonXiang2014** [comment]
我在乐视手机上也遇到这个问题，你在哪个型号的手机上遇到这个问题？在其他厂商的手机上能复现吗？
