### ISSUE TITLE
建议将服务启动到另外的进程中

### ISSUE THREAD

**Issue by imliujun** [ssseasonnn/RxDownload#148]
这样可以避免大量的资源下载占用主进程的内存

**Comment by imliujun** [comment]
我自己另外启动了一个 Service 进程，然后在这个 Service 中使用 RxDownload 报错了，我开启了RxDownload 的 enableService(true) 
```
java.lang.ClassCastException: android.os.BinderProxy cannot be cast to zlc.season.rxdownload3.core.DownloadService$DownloadBinder
                                                       at zlc.season.rxdownload3.core.RemoteMissionBox$startBindServiceAndDo$1.onServiceConnected(RemoteMissionBox.kt:160)
                                                       at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1818)
                                                       at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1847)
                                                       at android.os.Handler.handleCallback(Handler.java:808)
                                                       at android.os.Handler.dispatchMessage(Handler.java:101)
                                                       at android.os.Looper.loop(Looper.java:166)
                                                       at android.app.ActivityThread.main(ActivityThread.java:7396)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:926)
```

**Comment by ssseasonnn** [comment]
暂时没有支持跨进程
