### ISSUE TITLE
在代码中删除下载的文件后，重新下载失败open failed: ENOENT (No such file or directory)

### ISSUE THREAD

**Issue by adams-github** [ssseasonnn/RxDownload#164]
整个文件夹删除后，再重新下载文件，存储位置保存在之前删除夹当中，下载失败
E/RxDownload: Mission error! open failed: ENOENT (No such file or directory)
                                                                     java.io.IOException: open failed: ENOENT (No such file or directory)
                                                                         at java.io.File.createNewFile(File.java:950)
                                                                         at zlc.season.rxdownload3.core.RangeTmpFile.checkFile(RangeTmpFile.kt:42)
                                                                         at zlc.season.rxdownload3.core.RangeDownload.download(RangeDownload.kt:52)
                                                                         at zlc.season.rxdownload3.core.RealMission.download(RealMission.kt:269)
                                                                         at zlc.season.rxdownload3.core.RealMission.access$download(RealMission.kt:23)
                                                                         at zlc.season.rxdownload3.core.RealMission$checkAndDownload$1.apply(RealMission.kt:257)
                                                                         at zlc.season.rxdownload3.core.RealMission$checkAndDownload$1.apply(RealMission.kt:23)
                                                                         at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.onNext(FlowableFlatMap.java:132)
                                                                         at io.reactivex.internal.subscriptions.DeferredScalarSubscription.complete(DeferredScalarSubscription.java:133)
                                                                         at io.reactivex.internal.operators.maybe.MaybeToFlowable$MaybeToFlowableSubscriber.onSuccess(MaybeToFlowable.java:70)
                                                                         at io.reactivex.internal.operators.maybe.MaybeJust.subscribeActual(MaybeJust.java:36)
                                                                         at io.reactivex.Maybe.subscribe(Maybe.java:3730)
                                                                         at io.reactivex.internal.operators.maybe.MaybeToFlowable.subscribeActual(MaybeToFlowable.java:45)
                                                                         at io.reactivex.Flowable.subscribe(Flowable.java:12995)
                                                                         at io.reactivex.internal.operators.flowable.FlowableFlatMap.subscribeActual(FlowableFlatMap.java:53)
                                                                         at io.reactivex.Flowable.subscribe(Flowable.java:12995)
                                                                         at io.reactivex.Flowable.subscribe(Flowable.java:12941)
                                                                         at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.onNext(FlowableFlatMap.java:163)
                                                                         at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.onNext(FlowableSubscribeOn.java:97)
                                                                         at io.reactivex.internal.operators.flowable.FlowableDoOnLifecycle$SubscriptionLambdaSubscriber.onNext(FlowableDoOnLifecycle.java:79)
                                                                         at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.onNext(FlowableSubscribeOn.java:97)
                                                                         at io.reactivex.internal.subscriptions.ScalarSubscription.request(ScalarSubscription.java:55)
                                                                         at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.requestUpstream(FlowableSubscribeOn.java:133)
                                                                         at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.onSubscribe(FlowableSubscribeOn.java:90)
                                                                         at io.reactivex.internal.operators.flowable.FlowableJust.subscribeActual(FlowableJust.java:34)
                                                                         at io.reactivex.Flowable.subscribe(Flowable.java:12995)
                                                                         at io.reactivex.Flowable.subscribe(Flowable.java:12941)

**Comment by triple-stone** [comment]
同样遇到这个问题，demo也会出现，下载时候删除文件所在文件夹，状态变为失败就再也无法下载了，结束进程后重进才能恢复。

**Comment by lzp-punk** [comment]
已经解决这个问题了，删除文件时要调用clear（）来清除这个下载的任务，下次可以重新再开始下载

**Comment by triple-stone** [comment]
用户手动从文件管理器删除呢？

**Comment by triple-stone** [comment]
ok 我试试，多谢
