### ISSUE TITLE
华为荣耀6 安装报错 android4.4.2

### ISSUE THREAD

**Issue by ardenshu** [ssseasonnn/RxDownload#191]
java.lang.RuntimeException: Unable to get provider zlc.season.rxdownload3.helper.RxDownloadFileProvider: java.lang.ClassNotFoundException: Didn't find class "zlc.season.rxdownload3.helper.RxDownloadFileProvider" on path: DexPathList[[zip file "/data/app/com.taiyi.reborn-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.taiyi.reborn-2, /vendor/lib, /system/lib, /data/datalib]]
        at android.app.ActivityThread.installProvider(ActivityThread.java:5068)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:4654)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4594)
        at android.app.ActivityThread.access$1800(ActivityThread.java:139)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1316)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5314)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:680)
        at dalvik.system.NativeStart.main(Native Method)

**Comment by ardenshu** [comment]
已经解决了 MultiDex的问题
