### ISSUE TITLE
NoSuchElementException问题

### ISSUE THREAD

**Issue by xxchenqi** [ssseasonnn/RxDownload#193]
大佬问下，这个问题是 Extension还没初始化完成，实际上我是先初始化的，后调用的。
为什么还是报错？

Process: com.ideal.androidmdm.iemm, PID: 14824
                                                                           java.util.NoSuchElementException: Collection contains no element matching the predicate.
                                                                               at zlc.season.rxdownload3.core.RealMission.findExtension(RealMission.kt:294)
                                                                               at zlc.season.rxdownload3.core.LocalMissionBox.extension(LocalMissionBox.kt:127)
                                                                               at zlc.season.rxdownload3.core.DownloadService$DownloadBinder.extension(DownloadService.kt:82)
                                                                               at zlc.season.rxdownload3.core.RemoteMissionBox$extension$1$1.invoke(RemoteMissionBox.kt:127)
                                                                               at zlc.season.rxdownload3.core.RemoteMissionBox$extension$1$1.invoke(RemoteMissionBox.kt:21)
                                                                               at zlc.season.rxdownload3.core.RemoteMissionBox$startBindServiceAndDo$1.onServiceConnected(RemoteMissionBox.kt:161)
                                                                               at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1681)
                                                                               at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1710)
                                                                               at android.os.Handler.handleCallback(Handler.java:790)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                               at android.os.Looper.loop(Looper.java:192)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:6669)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:818)

**Comment by ssseasonnn** [comment]
把service关了呢？

**Comment by xxchenqi** [comment]
大佬指的是哪个service呀。。我自定义的Extension里没service。。
