### ISSUE TITLE
4.1.1 运行报错

### ISSUE THREAD

**Issue by weitto** [ssseasonnn/RxDownload#208]
07-05 06:46:27.682 1459-1459/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 java.lang.RuntimeException: Unable to get provider zlc.season.rxdownload3.helper.RxDownloadFileProvider: java.lang.ClassNotFoundException: zlc.season.rxdownload3.helper.RxDownloadFileProvider
                                                     at android.app.ActivityThread.installProvider(ActivityThread.java:4563)
                                                     at android.app.ActivityThread.installContentProviders(ActivityThread.java:4190)
                                                     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4132)
                                                     at android.app.ActivityThread.access$1300(ActivityThread.java:130)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1255)
                                                     at android.os.Handler.dispatchMessage(Handler.java:99)
                                                     at android.os.Looper.loop(Looper.java:137)
                                                     at android.app.ActivityThread.main(ActivityThread.java:4745)
                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:511)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
                                                     at dalvik.system.NativeStart.main(Native Method)
                                                  Caused by: java.lang.ClassNotFoundException: zlc.season.rxdownload3.helper.RxDownloadFileProvider
                                                     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:61)
                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
                                                     at android.app.ActivityThread.installProvider(ActivityThread.java:4548)
                                                     at android.app.ActivityThread.installContentProviders(ActivityThread.java:4190) 
                                                     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4132) 
                                                     at android.app.ActivityThread.access$1300(ActivityThread.java:130) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1255) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                     at android.os.Looper.loop(Looper.java:137) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:4745) 
                                                     at java.lang.reflect.Method.invokeNative(Native Method) 
                                                     at java.lang.reflect.Method.invoke(Method.java:511) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553) 
                                                     at dalvik.system.NativeStart.main(Native Method)

**Comment by weitto** [comment]
MultDex 造成的问题，4.4以上的没有问题，已经解决。

---https://blog.csdn.net/daitu_liang/article/details/72987378--
