### ISSUE TITLE
Breaks StrictMode on first run after install app

### ISSUE THREAD

**Issue by SylphiaWindy** [ssseasonnn/RxDownload#233]
E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
    java.lang.Throwable: Explicit termination method 'close' not called
        at dalvik.system.CloseGuard.open(CloseGuard.java:223)
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:263)
        at zlc.season.rxdownload3.core.RangeTargetFile.createShadowFile(RangeTargetFile.kt:45)
        at zlc.season.rxdownload3.core.RangeDownload.download(RangeDownload.kt:54)
        at zlc.season.rxdownload3.core.RealMission.download(RealMission.kt:280)
        at zlc.season.rxdownload3.core.RealMission.access$download(RealMission.kt:23)
        at zlc.season.rxdownload3.core.RealMission$checkAndDownload$1.apply(RealMission.kt:268)
        at zlc.season.rxdownload3.core.RealMission$checkAndDownload$1.apply(RealMission.kt:23)

**Comment by snailflying** [comment]
你这个需要把RxDownload.create()出来的disposable在页面关闭的时候dispose(disposable)一下

**Comment by SylphiaWindy** [comment]
Seems ok, close issue

**Comment by SylphiaWindy** [comment]
Dispose that disposable did not fix this issue.
Only crash on first run after a clean app install.

BTW I didn't find any code called close on the shadow file created.

https://github.com/ssseasonnn/RxDownload/blob/master/rxdownload3/src/main/java/zlc/season/rxdownload3/core/RangeTargetFile.kt#L45

`fun createShadowFile() {
        val file = RandomAccessFile(shadowFile, MODE)
        file.setLength(mission.totalSize)
    }`

that 'file' was only a local variable, thus leaked, you should make it a class member and close it for clean up.

**Comment by SylphiaWindy** [comment]
Dispose that disposable did not fix this issue.
Only crash on first run after a clean app install.

BTW I didn't find any code called close on the shadow file created.

https://github.com/ssseasonnn/RxDownload/blob/master/rxdownload3/src/main/java/zlc/season/rxdownload3/core/RangeTargetFile.kt#L45

fun createShadowFile() { val file = RandomAccessFile(shadowFile, MODE) file.setLength(mission.totalSize) }

that 'file' was only a local variable, thus leaked, you should make it a class member and close it for clean up.

**Comment by songliao-branch** [comment]
why is this closed? This is not fixed
