### ISSUE TITLE
unexpected end of stream 能否加入自动重试呢

### ISSUE THREAD

**Issue by aozaoz112233** [ssseasonnn/RxDownload#245]
已经发现是下载链接会在某个点读不到（demo中的链接）

不得不多次重新启动下载可最终完成

能否加入自动重试呢

java.net.ProtocolException: unexpected end of stream
        at okhttp3.internal.http1.Http1Codec$FixedLengthSource.read(Http1Codec.java:409)
        at okio.RealBufferedSource.read(RealBufferedSource.java:47)
        at okio.ForwardingSource.read(ForwardingSource.java:35)
        at retrofit2.OkHttpCall$ExceptionCatchingRequestBody$1.read(OkHttpCall.java:290)
        at okio.RealBufferedSource$1.read(RealBufferedSource.java:440)
        at java.io.InputStream.read(InputStream.java:101)
        at zlc.season.rxdownload3.core.RangeTargetFile$save$1.subscribe(RangeTargetFile.kt:74)

极易发生，即使在自带的demo中

发生于 RangeTargetFile 中  readLen = source.read(buffer)

**Comment by aozaoz112233** [comment]
好吧，我改了doOnError方法加入了一些Erro例外的条件

**Comment by aozaoz112233** [comment]
好吧，我改了doOnError方法加入了一些Erro例外的条件

**Comment by aozaoz112233** [comment]
好吧，我改了doOnError方法加入了一些Error例外的条件
