### ISSUE TITLE
开始暂停，开始暂停报错了android7.1.2

### ISSUE THREAD

**Issue by haira1987** [ssseasonnn/RxDownload#288]
io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | java.io.InterruptedIOException: interrupted
        at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
        at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.innerError(FlowableFlatMap.java:608)
        at io.reactivex.internal.operators.flowable.FlowableFlatMap$InnerSubscriber.onError(FlowableFlatMap.java:672)
        at io.reactivex.internal.operators.flowable.FlowableGenerate$GeneratorSubscription.onError(FlowableGenerate.java:189)
        at io.reactivex.internal.operators.flowable.FlowableGenerate$GeneratorSubscription.request(FlowableGenerate.java:114)
        at io.reactivex.internal.operators.flowable.FlowableFlatMap$InnerSubscriber.onSubscribe(FlowableFlatMap.java:656)
        at io.reactivex.internal.operators.flowable.FlowableGenerate.subscribeActual(FlowableGenerate.java:52)
        at io.reactivex.Flowable.subscribe(Flowable.java:14918)
        at io.reactivex.Flowable.subscribe(Flowable.java:14865)
        at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.onNext(FlowableFlatMap.java:163)
        at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.tryEmit(FlowableFlatMap.java:282)
        at io.reactivex.internal.operators.flowable.FlowableFlatMap$InnerSubscriber.onNext(FlowableFlatMap.java:663)
        at io.reactivex.internal.operators.flowable.FlowableOnBackpressureLatest$BackpressureLatestSubscriber.drain(FlowableOnBackpressureLatest.java:129)
        at io.reactivex.internal.operators.flowable.FlowableOnBackpressureLatest$BackpressureLatestSubscriber.onNext(FlowableOnBackpressureLatest.java:68)
        at io.reactivex.internal.operators.flowable.FlowableFromObservable$SubscriberObserver.onNext(FlowableFromObservable.java:54)
        at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeOnObserver.onNext(ObservableSubscribeOn.java:58)
        at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:47)
        at io.reactivex.Observable.subscribe(Observable.java:12267)
        at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
     Caused by: java.io.InterruptedIOException: interrupted
        at okio.Timeout.throwIfReached(Timeout.kt:98)
        at okio.InputStreamSource.read(Okio.kt:90)
        at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:159)
        at okio.RealBufferedSource.read(RealBufferedSource.kt:43)
        at okhttp3.internal.http1.Http1ExchangeCodec$AbstractSource.read(Http1ExchangeCodec.kt:352)
        at okhttp3.internal.http1.Http1ExchangeCodec$FixedLengthSource.read(Http1ExchangeCodec.kt:389)
        at okhttp3.internal.connection.Exchange$ResponseBodySource.read(Exchange.kt:279)
        at okio.RealBufferedSource.read(RealBufferedSource.kt:43)
        at okio.ForwardingSource.read(ForwardingSource.kt:29)
        at retrofit2.OkHttpCall$ExceptionCatchingResponseBody$1.read(OkHttpCall.java:288)
        at okio.RealBufferedSource$inputStream$1.read(RealBufferedSource.kt:440)
        at java.io.InputStream.read(InputStream.java:101)
2019-11-13 14:11:08.161 6584-6637/? E/AndroidRuntime:     at zlc.season.rxdownload4.downloader.RangeDownloader$InnerDownloader$rangeSave$2.accept(RangeDownloader.kt:144)
        at zlc.season.rxdownload4.downloader.RangeDownloader$InnerDownloader$rangeSave$2.accept(RangeDownloader.kt:116)
        at io.reactivex.internal.operators.flowable.FlowableInternalHelper$SimpleBiGenerator.apply(FlowableInternalHelper.java:62)
        at io.reactivex.internal.operators.flowable.FlowableInternalHelper$SimpleBiGenerator.apply(FlowableInternalHelper.java:53)
        at io.reactivex.internal.operators.flowable.FlowableGenerate$GeneratorSubscription.request(FlowableGenerate.java:109)
        	... 22 more

**Comment by ssseasonnn** [comment]
添加这段代码到Application里:
```kotlin
RxJavaPlugins.setErrorHandler {
            if (it is UndeliverableException) {
                //do nothing
            } else {
                it.log()
            }
        }
```

**Comment by haira1987** [comment]
我添加了，但连续点了4-5次开始，暂停，程序会卡死，会和这个有关系吗？点了通知栏的继续和取消也没用

**Comment by ssseasonnn** [comment]
不清楚, 跑下demo试试

**Comment by haira1987** [comment]
demo也卡住了，你的邮箱多少，我发你视频看看

**Comment by ssseasonnn** [comment]
ssseasonnn@gmail.com

**Comment by ssseasonnn** [comment]
有没有ANR日志, 发出来看下

**Comment by haira1987** [comment]
说来惭愧，不知道怎么获取ANR日志

**Comment by ssseasonnn** [comment]
看下手机这个目录下 有没有记录 /data/anr/

**Comment by ssseasonnn** [comment]
没有日志很难分析原因

**Comment by haira1987** [comment]
ANR日志发你邮箱了

**Comment by haira1987** [comment]
gmail邮箱能收到信息吗？收到回一下

**Comment by ssseasonnn** [comment]
收到了, 看样子好像是jdk7的一个bug, 我这儿没办法安装夜神模拟器, 你试试在demo里加上这个配置:
```kotlin
android{

     //加上这个
     kotlinOptions {
         jvmTarget = "1.8"
    }
}
```

**Comment by haira1987** [comment]
加上去了，还是不行。报了这个错
2019-11-13 17:51:49.322 1759-1759/? E/perfprofd: unable to open configuration file /data/data/com.google.android.gms/files/perfprofd.conf
2019-11-13 17:51:50.256 1807-1807/? E/SurfaceFlinger: hwcomposer module not found
2019-11-13 17:51:50.664 1813-1813/? E/CameraService: Could not load camera HAL module: -2 (No such file or directory)
2019-11-13 17:51:50.753 1812-1812/? E/RadioService: couldn't load radio module radio.primary (No such file or directory)
2019-11-13 17:51:50.753 1812-1812/? E/SoundTriggerHwService: couldn't load sound trigger module sound_trigger.primary (No such file or directory)
2019-11-13 17:51:51.467 1826-1826/? E/Netd: cannot find interface dummy0
2019-11-13 17:51:51.557 1826-1826/? E/Netd: Unable to create netlink socket: Protocol not supported
2019-11-13 17:51:52.457 1811-1811/? E/memtrack: Couldn't load memtrack module (No such file or directory)
2019-11-13 17:51:52.457 1811-1811/? E/android.os.Debug: failed to load memtrack module: -2
2019-11-13 17:51:52.925 1811-1811/? E/Typeface: Error mapping font file /system/fonts/DroidSansFallback.ttf
2019-11-13 17:51:54.157 1811-1811/? E/Zygote: Not whitelisted : /dev/ccid_ctrl
2019-11-13 17:51:54.627 2104-2104/? E/PowerManagerService-JNI: Couldn't load power module (No such file or directory)
2019-11-13 17:51:54.833 2104-2104/? E/art: DexFile_getDexOptNeeded file '/system/framework/org.apache.http.legacy.jar' does not exist
2019-11-13 17:51:55.802 2104-2104/? E/PackageManager: There should probably be a verifier, but, none were found
2019-11-13 17:51:55.915 2104-2120/? E/BatteryStatsService: power: gPowerModule not loaded
2019-11-13 17:51:55.920 2104-2117/? E/KernelCpuSpeedReader: Failed to read cpu-freq: /sys/devices/system/cpu/cpu0/cpufreq/stats/time_in_state (No such file or directory)
2019-11-13 17:51:55.920 2104-2117/? E/KernelUidCpuTimeReader: Failed to read uid_cputime: /proc/uid_cputime/show_uid_stat (No such file or directory)
2019-11-13 17:51:56.110 2104-2104/? E/ConsumerIrService: Can't open consumer IR HW Module, error: -2
2019-11-13 17:51:56.253 2104-2143/? E/EventHub: could not get driver version for /dev/input/mouse0, Not a typewriter
2019-11-13 17:51:56.476 2104-2143/? E/EventHub: could not get driver version for /dev/input/mice, Not a typewriter
2019-11-13 17:51:57.032 2104-2104/? E/WifiLogger: no ring buffers found
2019-11-13 17:51:57.032 2104-2104/? E/WifiLogger: Failed to start packet fate monitoring
2019-11-13 17:51:57.070 2104-2104/? E/IpConfigStore: Error parsing configuration: java.io.FileNotFoundException: /data/misc/ethernet/ipconfig.txt (No such file or directory)
2019-11-13 17:51:57.087 2104-2104/? E/ConnectivityService: Ignoring protectedNetwork 10
2019-11-13 17:51:57.087 2104-2104/? E/ConnectivityService: Ignoring protectedNetwork 11
2019-11-13 17:51:57.087 2104-2104/? E/ConnectivityService: Ignoring protectedNetwork 12
2019-11-13 17:51:57.087 2104-2104/? E/ConnectivityService: Ignoring protectedNetwork 14
2019-11-13 17:51:57.087 2104-2104/? E/ConnectivityService: Ignoring protectedNetwork 15
2019-11-13 17:51:57.330 2104-2135/? E/BatteryStatsService: power: gPowerModule not loaded
2019-11-13 17:51:57.331 2104-2117/? E/KernelCpuSpeedReader: Failed to read cpu-freq: /sys/devices/system/cpu/cpu0/cpufreq/stats/time_in_state (No such file or directory)
2019-11-13 17:51:57.331 2104-2117/? E/KernelUidCpuTimeReader: Failed to read uid_cputime: /proc/uid_cputime/show_uid_stat (No such file or directory)
2019-11-13 17:51:57.418 2104-2104/? E/HardwarePropertiesManagerService-JNI: Couldn't load thermal module (No such file or directory)
2019-11-13 17:51:57.463 2104-2104/? E/ContextHubService: ** Could not load context_hub module : err No such file or directory
2019-11-13 17:51:57.578 2104-2104/? E/LockSettingsStorage: Cannot read file java.io.FileNotFoundException: /data/system/gatekeeper.password.key: open failed: ENOENT (No such file or directory)
2019-11-13 17:51:57.578 2104-2104/? E/LockSettingsStorage: Cannot read file java.io.FileNotFoundException: /data/system/password.key: open failed: ENOENT (No such file or directory)
2019-11-13 17:51:57.578 2104-2104/? E/LockSettingsStorage: Cannot read file java.io.FileNotFoundException: /data/system/gatekeeper.pattern.key: open failed: ENOENT (No such file or directory)
2019-11-13 17:51:57.578 2104-2104/? E/LockSettingsStorage: Cannot read file java.io.FileNotFoundException: /data/system/gatekeeper.gesture.key: open failed: ENOENT (No such file or directory)
2019-11-13 17:51:57.582 2104-2104/? E/LockSettingsStorage: Cannot read file java.io.FileNotFoundException: /data/system/gesture.key: open failed: ENOENT (No such file or directory)
2019-11-13 17:51:58.168 2104-2104/? E/InputMethodManagerService: Ignoring updateSystemUiLocked due to an invalid token. uid:1000 token:null
2019-11-13 17:51:58.235 1826-2098/? E/SoftapController: Softap fwReload - NULL path for STA
2019-11-13 17:51:58.299 2104-2152/? E/WifiMonitor: killSupplicant p2pfalse init.svc.wpa_supplicant=unknown init.svc.p2p_supplicant=unknown
2019-11-13 17:51:58.315 2104-2152/? E/wifi: Can not initialize the vendor function pointer table
2019-11-13 17:51:58.315 2104-2152/? E/WifiNative-HAL: Could not start hal
2019-11-13 17:51:58.316 2104-2152/? E/WifiStateMachine: Failed to start HAL
2019-11-13 17:51:58.365 1811-1811/? E/Zygote: Not whitelisted : /dev/ccid_ctrl
2019-11-13 17:51:58.503 1811-1811/? E/Zygote: Not whitelisted : /dev/ccid_ctrl
2019-11-13 17:51:58.939 2190-2190/? E/wpa_supplicant: global ctrl interface @android:wpa_eth1 matches ctrl interface eth1 - do not open per-interface ctrl interface
2019-11-13 17:51:59.020 2104-2226/? E/WVMExtractor: Failed to open libwvm.so: dlopen failed: library "libwvm.so" not found
2019-11-13 17:51:59.245 2104-2152/? E/IpConfigStore: Error parsing configuration: java.io.FileNotFoundException: /data/misc/wifi/ipconfig.txt (No such file or directory)
2019-11-13 17:51:59.453 2104-2104/? E/NetdConnector: NDC Command {10 strict enable} took too long (718ms)
2019-11-13 17:51:59.560 2104-2152/? E/WifiLogger: no ring buffers found
2019-11-13 17:51:59.560 2104-2152/? E/WifiLogger: Failed to start packet fate monitoring
2019-11-13 17:51:59.724 2104-2120/? E/BatteryStatsService: no controller energy info supplied
2019-11-13 17:51:59.743 2104-2120/? E/KernelCpuSpeedReader: Failed to read cpu-freq: /sys/devices/system/cpu/cpu0/cpufreq/stats/time_in_state (No such file or directory)
2019-11-13 17:51:59.743 2104-2120/? E/KernelUidCpuTimeReader: Failed to read uid_cputime: /proc/uid_cputime/show_uid_stat (No such file or directory)
2019-11-13 17:51:59.755 2104-2120/? E/BatteryStatsService: no controller energy info supplied
2019-11-13 17:51:59.755 2104-2120/? E/KernelCpuSpeedReader: Failed to read cpu-freq: /sys/devices/system/cpu/cpu0/cpufreq/stats/time_in_state (No such file or directory)
2019-11-13 17:51:59.756 2104-2120/? E/KernelUidCpuTimeReader: Failed to read uid_cputime: /proc/uid_cputime/show_uid_stat (No such file or directory)
2019-11-13 17:52:00.065 2209-2241/? E/WVMExtractor: Failed to open libwvm.so: dlopen failed: library "libwvm.so" not found
2019-11-13 17:52:00.138 2104-2104/? E/LocationManagerService: no geocoder provider found
2019-11-13 17:52:00.140 2104-2104/? E/FlpHardwareProvider: Error hw_get_module 'flp': -2
2019-11-13 17:52:00.178 2104-2104/? E/ActivityRecognitionHardware: Error hw_get_module: -2
2019-11-13 17:52:00.179 2104-2104/? E/ActivityRecognitionProxy: ServiceWatcher could not start.
2019-11-13 17:52:00.250 2104-2116/? E/GnssLocationProvider: no AGPS interface in set_agps_server
2019-11-13 17:52:00.507 2104-2116/? E/GnssLocationProvider: no AGPS interface in set_agps_server
2019-11-13 17:52:00.513 1811-1811/? E/Zygote: Not whitelisted : /dev/ccid_ctrl
2019-11-13 17:52:00.900 1822-1848/? E/OMXNodeInstance: getParameter(71e0001:ffmpeg.aac.decoder, ??(0x6f400005)) ERROR: UnsupportedIndex(0x8000101a)
2019-11-13 17:52:01.000 1811-1811/? E/Zygote: Not whitelisted : /dev/ccid_ctrl
2019-11-13 17:52:01.043 1822-1822/? E/OMXNodeInstance: getExtensionIndex(71e000c:ffmpeg.divx.decoder, OMX.google.android.index.configureVideoTunnelMode) ERROR: UnsupportedIndex(0x8000101a)
2019-11-13 17:52:01.053 1822-1822/? E/OMXNodeInstance: getExtensionIndex(71e000d:ffmpeg.flv1.decoder, OMX.google.android.index.configureVideoTunnelMode) ERROR: UnsupportedIndex(0x8000101a)
2019-11-13 17:52:01.105 1822-1822/? E/OMXNodeInstance: getExtensionIndex(71e000e:ffmpeg.mpeg2.decoder, OMX.google.android.index.configureVideoTunnelMode) ERROR: UnsupportedIndex(0x8000101a)
2019-11-13 17:52:01.181 1822-1848/? E/OMXNodeInstance: getExtensionIndex(71e000f:ffmpeg.mpeg4.decoder, OMX.google.android.index.configureVideoTunnelMode) ERROR: UnsupportedIndex(0x8000101a)
2019-11-13 17:52:01.262 1822-1848/? E/OMXNodeInstance: getExtensionIndex(71e0010:ffmpeg.h263.decoder, OMX.google.android.index.configureVideoTunnelMode) ERROR: UnsupportedIndex(0x8000101a)
2019-11-13 17:52:01.338 1822-1848/? E/OMXNodeInstance: getExtensionIndex(71e0011:ffmpeg.hevc.decoder, OMX.google.android.index.configureVideoTunnelMode) ERROR: UnsupportedIndex(0x8000101a)
2019-11-13 17:52:01.363 1822-1848/? E/OMXNodeInstance: getExtensionIndex(71e0012:ffmpeg.vp8.decoder, OMX.google.android.index.configureVideoTunnelMode) ERROR: UnsupportedIndex(0x8000101a)
2019-11-13 17:52:01.398 1807-1807/? E/EGL_emulation: tid 1807: eglCreateSyncKHR(1489): error 0x3004 (EGL_BAD_ATTRIBUTE)
2019-11-13 17:52:01.404 1822-1848/? E/OMXNodeInstance: getExtensionIndex(71e0013:ffmpeg.rv.decoder, OMX.google.android.index.configureVideoTunnelMode) ERROR: UnsupportedIndex(0x8000101a)
2019-11-13 17:52:01.449 1822-1848/? E/OMXNodeInstance: getExtensionIndex(71e0014:ffmpeg.vc1.decoder, OMX.google.android.index.configureVideoTunnelMode) ERROR: UnsupportedIndex(0x8000101a)
2019-11-13 17:52:01.466 1822-1848/? E/OMXNodeInstance: getExtensionIndex(71e0015:ffmpeg.vtrial.decoder, OMX.google.android.index.configureVideoTunnelMode) ERROR: UnsupportedIndex(0x8000101a)
2019-11-13 17:52:01.498 1822-1848/? E/OMXNodeInstance: getExtensionIndex(71e0016:ffmpeg.wmv.decoder, OMX.google.android.index.configureVideoTunnelMode) ERROR: UnsupportedIndex(0x8000101a)
2019-11-13 17:52:02.202 2104-2352/? E/ActivityThread: Failed to find provider info for call_log
2019-11-13 17:52:02.400 2104-2116/? E/GnssLocationProvider: no AGPS interface in set_agps_server
2019-11-13 17:52:02.468 2104-2162/? E/ActivityThread: Failed to find provider info for com.android.calendar
2019-11-13 17:52:02.468 2104-2162/? E/ActivityThread: Failed to find provider info for com.android.calendar
2019-11-13 17:52:02.575 1822-1848/? E/OMXNodeInstance: getExtensionIndex(71e0024:google.mpeg4.decoder, OMX.google.android.index.configureVideoTunnelMode) ERROR: UnsupportedIndex(0x8000101a)
2019-11-13 17:52:02.635 1822-2265/? E/OMXNodeInstance: getExtensionIndex(71e0025:google.h263.decoder, OMX.google.android.index.configureVideoTunnelMode) ERROR: UnsupportedIndex(0x8000101a)
2019-11-13 17:52:02.714 1822-1822/? E/OMXNodeInstance: getExtensionIndex(71e0026:google.h264.decoder, OMX.google.android.index.configureVideoTunnelMode) ERROR: UnsupportedIndex(0x8000101a)
2019-11-13 17:52:02.784 1822-1822/? E/OMXNodeInstance: getExtensionIndex(71e0027:google.hevc.decoder, OMX.google.android.index.configureVideoTunnelMode) ERROR: UnsupportedIndex(0x8000101a)
2019-11-13 17:52:02.793 1822-1822/? E/OMXNodeInstance: getExtensionIndex(71e0028:google.vp8.decoder, OMX.google.android.index.configureVideoTunnelMode) ERROR: UnsupportedIndex(0x8000101a)
2019-11-13 17:52:02.808 1822-1822/? E/OMXNodeInstance: getExtensionIndex(71e0029:google.vp9.decoder, OMX.google.android.index.configureVideoTunnelMode) ERROR: UnsupportedIndex(0x8000101a)
2019-11-13 17:52:02.831 1822-1822/? E/OMXNodeInstance: getConfig(71e002a:google.h263.encoder, ConfigAndroidIntraRefresh(0x6f60000a)) ERROR: Undefined(0x80001001)
2019-11-13 17:52:02.887 1822-1848/? E/OMXNodeInstance: getConfig(71e002c:google.mpeg4.encoder, ConfigAndroidIntraRefresh(0x6f60000a)) ERROR: Undefined(0x80001001)
2019-11-13 17:52:02.900 1822-1822/? E/OMXNodeInstance: getConfig(71e002d:google.vp8.encoder, ConfigAndroidIntraRefresh(0x6f60000a)) ERROR: Undefined(0x80001001)
2019-11-13 17:52:03.328 2248-2400/? E/ActivityThread: Failed to find provider info for com.android.contacts
2019-11-13 17:52:04.323 2104-2162/? E/ActivityThread: Failed to find provider info for com.android.calendar
2019-11-13 17:52:04.327 2104-2162/? E/ActivityThread: Failed to find provider info for com.android.calendar
2019-11-13 17:52:05.188 2104-2116/? E/GnssLocationProvider: no AGPS interface in set_agps_server
2019-11-13 17:52:05.346 2248-2248/? E/PhoneInterfaceManager: [PhoneIntfMgr] getIccId: No UICC
2019-11-13 17:52:06.415 2248-2248/? E/PhoneInterfaceManager: [PhoneIntfMgr] getIccId: No UICC
2019-11-13 17:52:06.749 2104-2116/? E/GnssLocationProvider: no AGPS interface in set_agps_server
2019-11-13 17:52:06.801 2104-2116/? E/GnssLocationProvider: no AGPS interface in set_agps_server
2019-11-13 17:52:08.256 1813-1861/? E/CameraService: getCameraVendorTagDescriptor: camera hardware module doesn't exist
2019-11-13 17:52:08.480 2209-2454/? E/ActivityThread: Failed to find provider info for com.android.contacts
2019-11-13 17:52:08.665 2248-2248/? E/PhoneInterfaceManager: [PhoneIntfMgr] getIccId: No UICC
2019-11-13 17:52:08.749 2104-2116/? E/GnssLocationProvider: no AGPS interface in set_agps_server
2019-11-13 17:52:09.201 2248-2248/? E/PhoneInterfaceManager: [PhoneIntfMgr] getIccId: No UICC
2019-11-13 17:52:09.242 2248-2248/? E/PhoneInterfaceManager: [PhoneIntfMgr] getIccId: No UICC
2019-11-13 17:52:09.245 2104-2116/? E/GnssLocationProvider: no AGPS interface in set_agps_server
2019-11-13 17:52:09.623 2248-2248/? E/TelephonyProvider: Failed setting numeric '460071' to the current operator
2019-11-13 17:52:09.644 2248-2248/? E/TelephonyProvider: Failed setting numeric '460071' to the current operator
2019-11-13 17:52:09.682 2248-2248/? E/TelephonyProvider: Failed setting numeric '460071' to the current operator
2019-11-13 17:52:09.724 2104-2116/? E/GnssLocationProvider: no AGPS interface in set_agps_server
2019-11-13 17:52:09.873 2104-2116/? E/GnssLocationProvider: no AGPS interface in set_agps_server
2019-11-13 17:52:10.081 2104-2116/? E/GnssLocationProvider: no AGPS interface in set_agps_server
2019-11-13 17:52:10.635 1811-1811/? E/Zygote: Not whitelisted : /dev/ccid_ctrl
2019-11-13 17:52:10.929 2463-2463/? E/bootstat: Failed to read /data/misc/bootstat/post_decrypt_time_elapsed: No such file or directory
2019-11-13 17:52:10.929 2463-2463/? E/bootstat: Failed to parse boot time record: /data/misc/bootstat/post_decrypt_time_elapsed
2019-11-13 17:52:11.382 1811-1811/? E/Zygote: Not whitelisted : /dev/ccid_ctrl
2019-11-13 17:52:11.553 1811-1811/? E/Zygote: Not whitelisted : /dev/ccid_ctrl
2019-11-13 17:52:11.642 1811-1811/? E/Zygote: Not whitelisted : /dev/ccid_ctrl
2019-11-13 17:52:13.014 2104-2116/? E/GnssLocationProvider: no AGPS interface in set_agps_server
2019-11-13 17:52:14.049 2554-2554/? E/su: connect failed with 111: Connection refused
2019-11-13 17:52:15.094 2248-2248/? E/CarrierConfigLoader: java.io.FileNotFoundException: /data/user_de/0/com.android.phone/files/carrierconfig-com.android.carrierconfig-89860081011086266457.xml (No such file or directory)
2019-11-13 17:52:15.210 1811-1811/? E/Zygote: Not whitelisted : /dev/ccid_ctrl
2019-11-13 17:52:15.361 2104-2116/? E/GnssLocationProvider: no AGPS interface in set_agps_server
2019-11-13 17:52:15.428 1811-1811/? E/Zygote: Not whitelisted : /dev/ccid_ctrl
2019-11-13 17:52:17.797 2104-2116/? E/GnssLocationProvider: no AGPS interface in set_agps_server
2019-11-13 17:52:17.926 2104-2152/? E/WifiNative-HAL: setBssidBlacklist cmd 0 size 0
2019-11-13 17:52:17.955 2104-2152/? E/WifiStateMachine: Did not find remoteAddress {172.17.100.2} in /proc/net/arp
2019-11-13 17:52:18.454 1811-1811/? E/Zygote: Not whitelisted : /dev/ccid_ctrl
2019-11-13 17:52:18.456 2248-2248/? E/CarrierConfigLoader: java.io.FileNotFoundException: /data/user_de/0/com.android.phone/files/carrierconfig-com.android.carrierconfig-89860081011086266457.xml (No such file or directory)
2019-11-13 17:52:18.833 1811-1811/? E/Zygote: Not whitelisted : /dev/ccid_ctrl
2019-11-13 17:52:19.744 2104-2156/? E/NetdConnector: NDC Command {21 network interface add 100 eth1} took too long (1798ms)
2019-11-13 17:52:20.612 1811-1811/? E/Zygote: Not whitelisted : /dev/ccid_ctrl
2019-11-13 17:52:20.950 2191-2200/? E/sdcard: opendir /data/media/0/Apps failed: Permission denied
2019-11-13 17:52:20.951 2191-2200/? E/sdcard: opendir /data/media/0/Others failed: Permission denied
2019-11-13 17:52:21.420 2104-2156/? E/ConnectivityService: Exception in setupDataActivityTracking java.lang.IllegalStateException: command '25 idletimer add eth1 15 1' failed with '400 25 Failed to add interface'
2019-11-13 17:52:23.308 1811-1811/? E/Zygote: Not whitelisted : /dev/ccid_ctrl
2019-11-13 17:52:23.713 2104-2435/? E/ActivityManager: Sending non-protected broadcast com.vphone.launcher.MYAPPWIDGET_UPDATE from system 2504:com.vphone.launcher/1000 pkg com.vphone.launcher
    java.lang.Throwable
        at com.android.server.am.ActivityManagerService.checkBroadcastFromSystem(ActivityManagerService.java:17970)
        at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:18556)
        at com.android.server.am.ActivityManagerService.broadcastIntent(ActivityManagerService.java:18650)
        at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:499)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2807)
        at android.os.Binder.execTransact(Binder.java:565)
2019-11-13 17:52:23.731 2104-2135/? E/ActivityManager: Sending non-protected broadcast com.vphone.launcher.MYAPPWIDGET_UPDATE from system 2504:com.vphone.launcher/1000 pkg com.vphone.launcher
    java.lang.Throwable
        at com.android.server.am.ActivityManagerService.checkBroadcastFromSystem(ActivityManagerService.java:17970)
        at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:18556)
        at com.android.server.am.ActivityManagerService.broadcastIntent(ActivityManagerService.java:18650)
        at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:499)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2807)
        at android.os.Binder.execTransact(Binder.java:565)
2019-11-13 17:52:23.775 2504-2504/com.vphone.launcher E/libEGL: call to OpenGL ES API with no current context (logged once per thread)
2019-11-13 17:52:23.842 2104-2563/? E/ActivityManager: Sending non-protected broadcast com.vphone.launcher.MYAPPWIDGET_UPDATE from system 2504:com.vphone.launcher/1000 pkg com.vphone.launcher
    java.lang.Throwable
        at com.android.server.am.ActivityManagerService.checkBroadcastFromSystem(ActivityManagerService.java:17970)
        at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:18556)
        at com.android.server.am.ActivityManagerService.broadcastIntent(ActivityManagerService.java:18650)
        at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:499)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2807)
        at android.os.Binder.execTransact(Binder.java:565)
2019-11-13 17:52:24.584 1811-1811/? E/Zygote: Not whitelisted : /dev/ccid_ctrl
2019-11-13 17:52:26.222 2191-2200/? E/sdcard: opendir /data/media/0/Apps failed: Permission denied
2019-11-13 17:52:26.223 2191-2200/? E/sdcard: opendir /data/media/0/Others failed: Permission denied
2019-11-13 17:52:26.785 2104-2597/? E/ActivityManager: Sending non-protected broadcast com.bignox.app.store.hd.download.start from system 2752:com.bignox.app.store.hd/1000 pkg com.bignox.app.store.hd
    java.lang.Throwable
        at com.android.server.am.ActivityManagerService.checkBroadcastFromSystem(ActivityManagerService.java:17970)
        at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:18451)
        at com.android.server.am.ActivityManagerService.broadcastIntent(ActivityManagerService.java:18650)
        at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:499)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2807)
        at android.os.Binder.execTransact(Binder.java:565)
2019-11-13 17:52:26.801 2104-2597/? E/ActivityManager: Sending non-protected broadcast com.bignox.app.store.hd.download.start from system 2752:com.bignox.app.store.hd/1000 pkg com.bignox.app.store.hd
    java.lang.Throwable
        at com.android.server.am.ActivityManagerService.checkBroadcastFromSystem(ActivityManagerService.java:17970)
        at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:18556)
        at com.android.server.am.ActivityManagerService.broadcastIntent(ActivityManagerService.java:18650)
        at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:499)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2807)
        at android.os.Binder.execTransact(Binder.java:565)
2019-11-13 17:53:34.938 2998-2998/? E/studio.deploy: Could not get package user id: run-as: Package 'zlc.season.rxdownload.kotlin_demo' is unknown
2019-11-13 17:53:39.204 2982-2982/? E/memtrack: Couldn't load memtrack module (No such file or directory)
2019-11-13 17:53:39.204 2982-2982/? E/android.os.Debug: failed to load memtrack module: -2
2019-11-13 17:53:39.206 3003-3003/? E/memtrack: Couldn't load memtrack module (No such file or directory)
2019-11-13 17:53:39.206 3003-3003/? E/android.os.Debug: failed to load memtrack module: -2
2019-11-13 17:53:39.517 2998-2998/? E/studio.deploy: Could not find apks for package: zlc.season.rxdownload.kotlin_demo
2019-11-13 17:53:41.017 1811-1811/? E/Zygote: Not whitelisted : /dev/ccid_ctrl
2019-11-13 17:53:46.926 1811-1811/? E/Zygote: Not whitelisted : /dev/ccid_ctrl
2019-11-13 17:53:52.328 3061-3061/? E/memtrack: Couldn't load memtrack module (No such file or directory)
2019-11-13 17:53:52.328 3061-3061/? E/android.os.Debug: failed to load memtrack module: -2
2019-11-13 17:53:52.793 1811-1811/? E/Zygote: Not whitelisted : /dev/ccid_ctrl
2019-11-13 18:04:08.781 2104-3240/? E/AudioTrack: did not receive expected priority boost on time
2019-11-13 18:04:11.856 2104-3245/? E/AudioTrack: did not receive expected priority boost on time
2019-11-13 18:04:14.024 2104-3250/? E/AudioTrack: did not receive expected priority boost on time

**Comment by ssseasonnn** [comment]
还是卡死吗?  这段日志和卡死没什么关系

**Comment by haira1987** [comment]
还是卡死

**Comment by ssseasonnn** [comment]
排查了一下原因, 这是该模拟器的bug, 这是原生JDK7的一个BUG, 而通过查看Android的源码发现, Android的JDK源码对这部分代码进行了修改, 所以在真正的Android手机上不会出现这个问题, 我估计是夜神模拟器定制操作系统镜像的时候没有全部使用Android的源码

**Comment by ssseasonnn** [comment]
参考资料: 
[JDK-8024833 : (fc) FileChannel.map does not handle async close/interrupt correctly](https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8024833)

[Android 7.1.2系统FileChannelmpk源码](http://androidxref.com/7.1.2_r36/xref/libcore/ojluni/src/main/java/sun/nio/ch/FileChannelImpl.java#map)

**Comment by haira1987** [comment]
好的，明白了，谢谢
