### ISSUE TITLE
Getting message from throwable

### ISSUE THREAD

**Issue by nana-desu** [ssseasonnn/RxDownload#308]
I need to get throwable from Failed status "Response body is NULL"
But can't receive that error using throwable as you said in the documentation page

Here's the log
```
W/RxDownload: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | io.reactivex.exceptions.CompositeException: 15 exceptions occurred. 
    io.reactivex.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | io.reactivex.exceptions.CompositeException: 15 exceptions occurred. 
        at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
        at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
        at io.reactivex.internal.subscribers.LambdaSubscriber.onError(LambdaSubscriber.java:79)
        at io.reactivex.internal.operators.flowable.FlowableDoOnLifecycle$SubscriptionLambdaSubscriber.onError(FlowableDoOnLifecycle.java:85)
        at io.reactivex.internal.operators.flowable.FlowableDoOnEach$DoOnEachSubscriber.onError(FlowableDoOnEach.java:111)
        at io.reactivex.internal.operators.flowable.FlowableDoOnEach$DoOnEachSubscriber.onError(FlowableDoOnEach.java:111)
        at io.reactivex.internal.operators.flowable.FlowableDoOnEach$DoOnEachSubscriber.onError(FlowableDoOnEach.java:111)
        at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.checkTerminated(FlowableObserveOn.java:209)
        at io.reactivex.internal.operators.flowable.FlowableObserveOn$ObserveOnSubscriber.runAsync(FlowableObserveOn.java:399)
        at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:176)
        at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:124)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: io.reactivex.exceptions.CompositeException: 15 exceptions occurred. 
        at io.reactivex.internal.util.ExceptionHelper.addThrowable(ExceptionHelper.java:67)
        at io.reactivex.internal.util.AtomicThrowable.addThrowable(AtomicThrowable.java:34)
        at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.innerError(FlowableFlatMap.java:603)
        at io.reactivex.internal.operators.flowable.FlowableFlatMap$InnerSubscriber.onError(FlowableFlatMap.java:677)
        at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.checkTerminate(FlowableFlatMap.java:572)
        at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.drainLoop(FlowableFlatMap.java:379)
        at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.drain(FlowableFlatMap.java:371)
        at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.onError(FlowableFlatMap.java:330)
        at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.onNext(FlowableFlatMap.java:136)
        at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.tryEmit(FlowableFlatMap.java:282)
        at io.reactivex.internal.operators.flowable.FlowableFlatMap$InnerSubscriber.onNext(FlowableFlatMap.java:668)
        at io.reactivex.internal.operators.flowable.FlowableOnBackpressureLatest$BackpressureLatestSubscriber.drain(FlowableOnBackpressureLatest.java:129)
        at io.reactivex.internal.operators.flowable.FlowableOnBackpressureLatest$BackpressureLatestSubscriber.onNext(FlowableOnBackpressureLatest.java:68)
        at io.reactivex.internal.operators.flowable.FlowableFromObservable$SubscriberObserver.onNext(FlowableFromObservable.java:54)
        at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeOnObserver.onNext(ObservableSubscribeOn.java:58)
        at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:47)
        at io.reactivex.Observable.subscribe(Observable.java:12284)
        at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: io.reactivex.exceptions.CompositeException$CompositeExceptionCausalChain: Chain of Causes for CompositeException In Order Received =>
        at android.util.Log.printlns(Log.java:432)
        at android.util.Log.w(Log.java:208)
        at zlc.season.rxdownload4.utils.LogUtilKt.log(LogUtil.kt:12)
        at zlc.season.rxdownload4.utils.LogUtilKt.log$default(LogUtil.kt:9)
        at com.usamin.nekopoi.MainApp$onCreate$1.accept(MainApp.kt:28)
        at com.usamin.nekopoi.MainApp$onCreate$1.accept(MainApp.kt:16)
        at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:373)
        at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
        at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
        at io.reactivex.internal.subscribers.LambdaSubscriber.onError(LambdaSubscriber.java:79)
        at io.reactivex.internal.operators.flowable.FlowableDoOnLifecycle$SubscriptionLambdaSubscriber.onError(FlowableDoOnLifecycle.java:85)
        at io.reactivex.internal.operators.flowable.FlowableDoOnEach$DoOnEachSubscriber.onError(FlowableDoOnEach.java:111)
        at io.reactivex.internal.operators.flowable.FlowableDoOnEach$DoOnEachSubscriber.onError(FlowableDoOnEach.java:111)
        at io.reactivex.internal.operators.flowable.FlowableDoOnEach$DoOnEachSubscriber.onError(FlowableDoOnEach.java:111)
        at io.reactivex.internal.operators.flowable.FlowableDoOnLifecycle$SubscriptionLambdaSubscriber.onError(FlowableDoOnLifecycle.java:85)
        at io.reactivex.subscribers.SerializedSubscriber.onError(SerializedSubscriber.java:142)
        at io.reactivex.internal.operators.flowable.FlowableSampleTimed$SampleTimedSubscriber.onError(FlowableSampleTimed.java:93)
        at io.reactivex.internal.operators.flowable.FlowablePublish$PublishSubscriber.checkTerminated(FlowablePublish.java:404)
        at io.reactivex.internal.operators.flowable.FlowablePublish$PublishSubscriber.dispatch(FlowablePublish.java:462)
        at io.reactivex.internal.operators.flowable.FlowablePublish$PublishSubscriber.onError(FlowablePublish.java:257)
        at io.reactivex.internal.operators.flowable.FlowableDoFinally$DoFinallySubscriber.onError(FlowableDoFinally.java:89)
        at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.checkTerminate(FlowableFlatMap.java:572)
        at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.drainLoop(FlowableFlatMap.java:379)
        at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.drain(FlowableFlatMap.java:371)
        at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.innerError(FlowableFlatMap.java:611)
        at io.reactivex.internal.operators.flowable.FlowableFlatMap$InnerSubscriber.onError(FlowableFlatMap.java:677)
        at io.reactivex.internal.operators.flowable.FlowableDoOnEach$DoOnEachSubscriber.onError(FlowableDoOnEach.java:111)
        at io.reactivex.internal.subscribers.BasicFuseableSubscriber.onError(BasicFuseableSubscriber.java:101)
        at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.drainLoop(FlowableFlatMap.java:433)
W/RxDownload:     at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.drain(FlowableFlatMap.java:371)
        at io.reactivex.internal.operators.flowable.FlowableFlatMap$InnerSubscriber.onComplete(FlowableFlatMap.java:683)
        at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.drainLoop(FlowableFlatMap.java:431)
        at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.drain(FlowableFlatMap.java:371)
        at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.onComplete(FlowableFlatMap.java:343)
        at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.drainLoop(FlowableFlatMap.java:431)
        at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.drain(FlowableFlatMap.java:371)
        at io.reactivex.internal.operators.flowable.FlowableFlatMap$InnerSubscriber.onComplete(FlowableFlatMap.java:683)
        at io.reactivex.internal.operators.flowable.FlowableOnBackpressureLatest$BackpressureLatestSubscriber.checkTerminated(FlowableOnBackpressureLatest.java:163)
        at io.reactivex.internal.operators.flowable.FlowableOnBackpressureLatest$BackpressureLatestSubscriber.drain(FlowableOnBackpressureLatest.java:121)
        at io.reactivex.internal.operators.flowable.FlowableOnBackpressureLatest$BackpressureLatestSubscriber.onComplete(FlowableOnBackpressureLatest.java:81)
        at io.reactivex.internal.operators.flowable.FlowableFromObservable$SubscriberObserver.onComplete(FlowableFromObservable.java:44)
        at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeOnObserver.onComplete(ObservableSubscribeOn.java:68)
        at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:51)
        	... 10 more
     Caused by: java.lang.RuntimeException: Response body is NULL
        at zlc.season.rxdownload4.downloader.RangeDownloader$InnerDownloader.rangeSave(RangeDownloader.kt:143)
        at zlc.season.rxdownload4.downloader.RangeDownloader$InnerDownloader.access$rangeSave(RangeDownloader.kt:123)
        at zlc.season.rxdownload4.downloader.RangeDownloader$InnerDownloader$download$3.apply(RangeDownloader.kt:135)
        at zlc.season.rxdownload4.downloader.RangeDownloader$InnerDownloader$download$3.apply(RangeDownloader.kt:123)
        at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.onNext(FlowableFlatMap.java:132)
        at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.tryEmit(FlowableFlatMap.java:282)
        at io.reactivex.internal.operators.flowable.FlowableFlatMap$InnerSubscriber.onNext(FlowableFlatMap.java:668)
        at io.reactivex.internal.operators.flowable.FlowableOnBackpressureLatest$BackpressureLatestSubscriber.drain(FlowableOnBackpressureLatest.java:129)
        at io.reactivex.internal.operators.flowable.FlowableOnBackpressureLatest$BackpressureLatestSubscriber.onNext(FlowableOnBackpressureLatest.java:68)
        at io.reactivex.internal.operators.flowable.FlowableFromObservable$SubscriberObserver.onNext(FlowableFromObservable.java:54)
        at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeOnObserver.onNext(ObservableSubscribeOn.java:58)
        at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:47)
        at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.onComplete(FlowableFlatMap.java:343) 
        at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.drainLoop(FlowableFlatMap.java:431) 
        at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.drain(FlowableFlatMap.java:371) 
        at io.reactivex.internal.operators.flowable.FlowableFlatMap$InnerSubscriber.onComplete(FlowableFlatMap.java:683) 
        at io.reactivex.internal.operators.flowable.FlowableOnBackpressureLatest$BackpressureLatestSubscriber.checkTerminated(FlowableOnBackpressureLatest.java:163) 
        at io.reactivex.internal.operators.flowable.FlowableOnBackpressureLatest$BackpressureLatestSubscriber.drain(FlowableOnBackpressureLatest.java:121) 
        at io.reactivex.internal.operators.flowable.FlowableOnBackpressureLatest$BackpressureLatestSubscriber.onComplete(FlowableOnBackpressureLatest.java:81) 
        at io.reactivex.internal.operators.flowable.FlowableFromObservable$SubscriberObserver.onComplete(FlowableFromObservable.java:44) 
        at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeOnObserver.onComplete(ObservableSubscribeOn.java:68) 
        at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:51) 

```

**Comment by nana-desu** [comment]
```
java.net.SocketException: Socket closed
        at com.google.android.gms.org.conscrypt.NativeCrypto.SSL_read(:com.google.android.gms@200616028@20.06.16 (100400-296104215):-2)
        at com.google.android.gms.org.conscrypt.NativeSsl.read(:com.google.android.gms@200616028@20.06.16 (100400-296104215):3)
        at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket$SSLInputStream.read(:com.google.android.gms@200616028@20.06.16 (100400-296104215):7)
        at okio.InputStreamSource.read(Okio.kt:93)
        at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:129)
        at okio.RealBufferedSource.read(RealBufferedSource.kt:188)
        at okhttp3.internal.http1.Http1ExchangeCodec$AbstractSource.read(Http1ExchangeCodec.kt:349)
        at okhttp3.internal.http1.Http1ExchangeCodec$FixedLengthSource.read(Http1ExchangeCodec.kt:386)
        at okhttp3.internal.connection.Exchange$ResponseBodySource.read(Exchange.kt:276)
        at okio.RealBufferedSource.read(RealBufferedSource.kt:188)
        at okio.ForwardingSource.read(ForwardingSource.kt:29)
        at retrofit2.OkHttpCall$ExceptionCatchingResponseBody$1.read(OkHttpCall.java:288)
        at okio.RealBufferedSource$inputStream$1.read(RealBufferedSource.kt:158)
        at java.io.InputStream.read(InputStream.java:101)
        at zlc.season.rxdownload4.downloader.RangeDownloader$InnerDownloader$rangeSave$2.accept(RangeDownloader.kt:152)
        at zlc.season.rxdownload4.downloader.RangeDownloader$InnerDownloader$rangeSave$2.accept(RangeDownloader.kt:123)
        at io.reactivex.internal.operators.flowable.FlowableInternalHelper$SimpleBiGenerator.apply(FlowableInternalHelper.java:62)
        at io.reactivex.internal.operators.flowable.FlowableInternalHelper$SimpleBiGenerator.apply(FlowableInternalHelper.java:53)
        at io.reactivex.internal.operators.flowable.FlowableGenerate$GeneratorSubscription.request(FlowableGenerate.java:109)
        at io.reactivex.internal.operators.flowable.FlowableFlatMap$InnerSubscriber.onSubscribe(FlowableFlatMap.java:661)
        at io.reactivex.internal.operators.flowable.FlowableGenerate.subscribeActual(FlowableGenerate.java:52)
        at io.reactivex.Flowable.subscribe(Flowable.java:14935)
        at io.reactivex.Flowable.subscribe(Flowable.java:14882)
        at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.onNext(FlowableFlatMap.java:163)
        at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.tryEmit(FlowableFlatMap:282)
        at io.reactivex.internal.operators.flowable.FlowableFlatMap$InnerSubscriber.onNext(FlowableFlatMap.java:668)
        at io.reactivex.internal.operators.flowable.FlowableOnBackpressureLatest$BackpressureLatestSubscriber.drain(FlowableOnBackpressureLatest.java:129)
        at io.reactivex.internal.operators.flowable.FlowableOnBackpressureLatest$BackpressureLatestSubscriber.onNext(FlowableOnBackpressureLatest.java:68)
        at io.reactivex.internal.operators.flowable.FlowableFromObservable$SubscriberObserver.onNext(FlowableFromObservable.java:54)
        at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeOnObserver.onNext(ObservableSubscribeOn.java:58)
        at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:47)
        at io.reactivex.Observable.subscribe(Observable.java:12284)
        at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
```

Please help. ASAP

**Comment by ssseasonnn** [comment]
When you receive the Failed status, it has a throwable property that represents the error that occurred.
<img width="554" alt="image" src="https://user-images.githubusercontent.com/10646230/77505203-79c38900-6e9d-11ea-9c27-10138748f905.png">

**Comment by ssseasonnn** [comment]
Are you using Basic Download? This [io.reactivex.exceptions.OnErrorNotImplementedException] exception indicates that you need to provide an onError callback.

**Comment by nana-desu** [comment]
I use task manager, my code looks like this
``
  Task(
      url = url, savePath = path, saveName = filename, taskName = filename
    ).manager(
      notificationCreator = SimpleNotificationCreator(),
      recorder = RoomRecorder(),
      taskLimitation = BasicTaskLimitation.of(6),
      maxConCurrency = concurrent
    ).apply {
      subscribe {
        when (it) {
          is Normal, is Started, is Completed, is Pending, is Downloading -> try {
            if (it.progress.isChunked) {
              this.stop()
            }
          } catch (e: Throwable) {
          }
          is Failed -> try {
            if (it.progress.isChunked) {
              this.stop()
            } else {
              this.stop()
              Handler().postDelayed({
                this.start()
              }, 1000)
            }
          } catch (e: Throwable) {
          }
        }
      }
      start()
    }
```

When getting throwable 
```
it.progress.throwable.message
```
it shows "io.reactivex.exceptions.CompositeException: 15 exceptions occurred"

**Comment by ssseasonnn** [comment]
em... why your server return a NULL ResponseBody?

**Comment by ssseasonnn** [comment]
```kotlin
val compositeException=CompositeException(xxx)
val throwableList = compositeException.getExceptions()
throwableList.forEach{
  if(it.message == Response body is NULL){
      return it
}
}
```

**Comment by nana-desu** [comment]
not my server, but the file hosting itself. 
![image](https://user-images.githubusercontent.com/59090734/77524765-7f7b9780-6eba-11ea-99e1-080f7515d173.png)

**Comment by nana-desu** [comment]
btw I have fixed issue with socket closed by adding to your code
```
internalState.apply {
                             try {
                                val buffer = ByteArray(8192)
                                val readLen = source.read(buffer)

                                if (readLen == -1) {
                                    emitter.onComplete()
                                } else {
                                    shadowFileBuffer.put(buffer, 0, readLen)

                                    current += readLen

                                    tmpFileBuffer.putLong(16, current)

                                    emitter.onNext(readLen.toLong())
                                }
                            } catch (e: SocketException) {
                                tmpFileChannel.closeQuietly()
                                shadowChannel.closeQuietly()
                                source.closeQuietly()
                            } catch (e: SocketTimeoutException) {
                                tmpFileChannel.closeQuietly()
                                shadowChannel.closeQuietly()
                                source.closeQuietly()
                            }
```

**Comment by nana-desu** [comment]
I hope you can implement retry times, so I don't need to use postDelayed.
When download status is paused due Response body is NULL then the download will resume again, but sometimes when starting an initial download, it gets looped in certain conditions

**Comment by ssseasonnn** [comment]
No problem, but have to wait for a while, I have been busy recently

**Comment by nana-desu** [comment]
I also wait for a fix on download failed exception.
On every activity I put 
```  
RxJavaPlugins.setErrorHandler {
      if (it is UndeliverableException) {
        //do nothing
      } else {
        it.log()
      }
    }


```
But crash still appears
![image](https://user-images.githubusercontent.com/59090734/77663521-bbdcef80-6faf-11ea-8d86-06c1dad04480.png)


```
when (it) {
      is Normal, is Started, is Completed, is Pending, is Downloading -> try {
        if (it.progress.isChunked) {
          task.stop()
        }
      } catch (e: Throwable) {
      }
      is Failed -> try {
        if (it.progress.isChunked) {
          task.stop()
        } else {
          task.stop()
          Handler().postDelayed({
            task.start()
          }, 1000)
        }
      } catch (e: Throwable) {
      }
    }
```

**Comment by ssseasonnn** [comment]
You can put it in Application instead of setting each Activity once

**Comment by nana-desu** [comment]
Yes, I also put in Application/BaseApp but still the same.
![image](https://user-images.githubusercontent.com/59090734/77877562-49566300-7280-11ea-97f5-b8a311a20b6a.png)

![image](https://user-images.githubusercontent.com/59090734/77877698-b2d67180-7280-11ea-9619-66af2d270c53.png)

**Comment by nana-desu** [comment]
any update?
also please fix for download, sometimes stops at 70% and corrupted when using zippyshare

**Comment by nana-desu** [comment]
any update? Sometimes downloads stuck or paused when starting download, or even while file downlod is in progress. Can you try with zippyshare?
