### ISSUE TITLE
有时候会出现：FATAL EXCEPTION: RxCachedThreadScheduler-3

### ISSUE THREAD

**Issue by laingdayi** [ssseasonnn/RxDownload#351]
E/AndroidRuntime: FATAL EXCEPTION: RxCachedThreadScheduler-3
    Process: com.aidl.recyclerview, PID: 26481
    io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | java.io.InterruptedIOException
        at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
        at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.innerError(FlowableFlatMap.java:608)
        at io.reactivex.internal.operators.flowable.FlowableFlatMap$InnerSubscriber.onError(FlowableFlatMap.java:672)
        at io.reactivex.internal.operators.flowable.FlowableGenerate$GeneratorSubscription.onError(FlowableGenerate.java:189)
        at io.reactivex.internal.operators.flowable.FlowableGenerate$GeneratorSubscription.request(FlowableGenerate.java:114)
        at io.reactivex.internal.operators.flowable.FlowableFlatMap$InnerSubscriber.onSubscribe(FlowableFlatMap.java:656)
        at io.reactivex.internal.operators.flowable.FlowableGenerate.subscribeActual(FlowableGenerate.java:52)
        at io.reactivex.Flowable.subscribe(Flowable.java:14918)
        at io.reactivex.Flowable.subscribe(Flowable.java:14865)

**Comment by laingdayi** [comment]
在下载过程中，点击暂停的时候会出现该报错

**Comment by ssseasonnn** [comment]
这个错误是正常的，你配置一个全局的RxJavaErrorHandler捕获住就可以了

**Comment by laingdayi** [comment]
好的，谢谢
