### ISSUE TITLE
Got Error on Huawei V8.

### ISSUE THREAD

**Issue by floatingmuseum** [ssseasonnn/RxDownload#41]
Code:
```java
        disposable = RxDownload.getInstance(this)
                .maxThread(5)//5线程
                .maxRetryCount(3)//错误重试次数
                .download(currentUrl)
                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(new Consumer<DownloadStatus>() {
                    @Override
                    public void accept(@NonNull DownloadStatus status) throws Exception {
                        Logger.d("RxDownload信息...DownloadSize:" + status.getDownloadSize() + "...TotalSize" + status.getTotalSize() + "...Percent" + status.getPercentNumber());
                        pbDownload.setProgress((int) status.getPercentNumber());
                        tvNetSpeed.setText(status.getFormatDownloadSize() + "/" + status.getFormatTotalSize());
                    }
                }, new Consumer<Throwable>() {
                    @Override
                    public void accept(@NonNull Throwable throwable) throws Exception {
                        Logger.d("RxDownload信息...onError");
                        throwable.printStackTrace();
                    }
                }, new Action() {
                    @Override
                    public void run() throws Exception {
                        long time = System.currentTimeMillis() - startTime;
                        long resultTime = time / 1000;
                        Logger.d("RxDownload信息...onComplete:耗时" + resultTime);
                    }
                });
```

Exception:
```java
03-08 16:23:05.185 29448-29448/com.floatingmuseum.androidtest W/System.err: java.io.FileNotFoundException: /storage/emulated/0/Download/.cache/3c5d8fe0-4f1d-4f4e-b7c5-59f2c4b4e9fd.apk.lmf: open failed: ENOENT (No such file or directory)
03-08 16:23:05.185 29448-29448/com.floatingmuseum.androidtest W/System.err:     at libcore.io.IoBridge.open(IoBridge.java:455)
03-08 16:23:05.185 29448-29448/com.floatingmuseum.androidtest W/System.err:     at java.io.RandomAccessFile.<init>(RandomAccessFile.java:247)
03-08 16:23:05.185 29448-29448/com.floatingmuseum.androidtest W/System.err:     at zlc.season.rxdownload2.function.FileHelper.writeLastModify(FileHelper.java:295)
03-08 16:23:05.185 29448-29448/com.floatingmuseum.androidtest W/System.err:     at zlc.season.rxdownload2.function.FileHelper.prepareDownload(FileHelper.java:107)
03-08 16:23:05.185 29448-29448/com.floatingmuseum.androidtest W/System.err:     at zlc.season.rxdownload2.entity.TemporaryRecord.prepareRangeDownload(TemporaryRecord.java:113)
03-08 16:23:05.185 29448-29448/com.floatingmuseum.androidtest W/System.err:     at zlc.season.rxdownload2.entity.DownloadType$MultiThreadDownload.prepareDownload(DownloadType.java:297)
03-08 16:23:05.185 29448-29448/com.floatingmuseum.androidtest W/System.err:     at zlc.season.rxdownload2.function.DownloadHelper.download(DownloadHelper.java:134)
03-08 16:23:05.185 29448-29448/com.floatingmuseum.androidtest W/System.err:     at zlc.season.rxdownload2.function.DownloadHelper.access$200(DownloadHelper.java:43)
03-08 16:23:05.185 29448-29448/com.floatingmuseum.androidtest W/System.err:     at zlc.season.rxdownload2.function.DownloadHelper$3.apply(DownloadHelper.java:115)
03-08 16:23:05.185 29448-29448/com.floatingmuseum.androidtest W/System.err:     at zlc.season.rxdownload2.function.DownloadHelper$3.apply(DownloadHelper.java:112)
03-08 16:23:05.185 29448-29448/com.floatingmuseum.androidtest W/System.err:     at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.onNext(ObservableFlatMap.java:121)
03-08 16:23:05.185 29448-29448/com.floatingmuseum.androidtest W/System.err:     at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.tryEmit(ObservableFlatMap.java:262)
03-08 16:23:05.185 29448-29448/com.floatingmuseum.androidtest W/System.err:     at io.reactivex.internal.operators.observable.ObservableFlatMap$InnerObserver.onNext(ObservableFlatMap.java:554)
03-08 16:23:05.185 29448-29448/com.floatingmuseum.androidtest W/System.err:     at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.drainLoop(ObservableFlatMap.java:434)
03-08 16:23:05.185 29448-29448/com.floatingmuseum.androidtest W/System.err:     at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.drain(ObservableFlatMap.java:323)
03-08 16:23:05.185 29448-29448/com.floatingmuseum.androidtest W/System.err:     at io.reactivex.internal.operators.observable.ObservableFlatMap$InnerObserver.onSubscribe(ObservableFlatMap.java:541)
03-08 16:23:05.185 29448-29448/com.floatingmuseum.androidtest W/System.err:     at io.reactivex.internal.operators.observable.ObservableScalarXMap$ScalarXMapObservable.subscribeActual(ObservableScalarXMap.java:163)
03-08 16:23:05.185 29448-29448/com.floatingmuseum.androidtest W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:10700)
03-08 16:23:05.185 29448-29448/com.floatingmuseum.androidtest W/System.err:     at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.subscribeInner(ObservableFlatMap.java:162)
03-08 16:23:05.185 29448-29448/com.floatingmuseum.androidtest W/System.err:     at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.onNext(ObservableFlatMap.java:139)
03-08 16:23:05.185 29448-29448/com.floatingmuseum.androidtest W/System.err:     at io.reactivex.internal.operators.observable.ObservableDoOnEach$DoOnEachObserver.onNext(ObservableDoOnEach.java:103)
03-08 16:23:05.185 29448-29448/com.floatingmuseum.androidtest W/System.err:     at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.tryEmit(ObservableFlatMap.java:262)
03-08 16:23:05.185 29448-29448/com.floatingmuseum.androidtest W/System.err:     at io.reactivex.internal.operators.observable.ObservableFlatMap$InnerObserver.onNext(ObservableFlatMap.java:554)
03-08 16:23:05.185 29448-29448/com.floatingmuseum.androidtest W/System.err:     at io.reactivex.internal.operators.observable.ObservableRetryBiPredicate$RetryBiObserver.onNext(ObservableRetryBiPredicate.java:66)
03-08 16:23:05.185 29448-29448/com.floatingmuseum.androidtest W/System.err:     at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:64)
03-08 16:23:05.185 29448-29448/com.floatingmuseum.androidtest W/System.err:     at io.reactivex.internal.operators.observable.ObservableDoOnEach$DoOnEachObserver.onNext(ObservableDoOnEach.java:103)
03-08 16:23:05.185 29448-29448/com.floatingmuseum.androidtest W/System.err:     at com.jakewharton.retrofit2.adapter.rxjava2.CallObservable.subscribeActual(CallObservable.java:43)
03-08 16:23:05.185 29448-29448/com.floatingmuseum.androidtest W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:10700)
03-08 16:23:05.185 29448-29448/com.floatingmuseum.androidtest W/System.err:     at io.reactivex.internal.operators.observable.ObservableDoOnEach.subscribeActual(ObservableDoOnEach.java:42)
03-08 16:23:05.185 29448-29448/com.floatingmuseum.androidtest W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:10700)
03-08 16:23:05.185 29448-29448/com.floatingmuseum.androidtest W/System.err:     at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:33)
03-08 16:23:05.185 29448-29448/com.floatingmuseum.androidtest W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:10700)
03-08 16:23:05.185 29448-29448/com.floatingmuseum.androidtest W/System.err:     at io.reactivex.internal.operators.observable.ObservableRetryBiPredicate$RetryBiObserver.subscribeNext(ObservableRetryBiPredicate.java:100)
03-08 16:23:05.185 29448-29448/com.floatingmuseum.androidtest W/System.err:     at io.reactivex.internal.operators.observable.ObservableRetryBiPredicate.subscribeActual(ObservableRetryBiPredicate.java:39)
03-08 16:23:05.185 29448-29448/com.floatingmuseum.androidtest W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:10700)
03-08 16:23:05.185 29448-29448/com.floatingmuseum.androidtest W/System.err:     at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.subscribeInner(ObservableFlatMap.java:162)
03-08 16:23:05.185 29448-29448/com.floatingmuseum.androidtest W/System.err:     at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.onNext(ObservableFlatMap.java:139)
03-08 16:23:05.186 29448-29448/com.floatingmuseum.androidtest W/System.err:     at io.reactivex.internal.operators.observable.ObservableRetryBiPredicate$RetryBiObserver.onNext(ObservableRetryBiPredicate.java:66)
03-08 16:23:05.186 29448-29448/com.floatingmuseum.androidtest W/System.err:     at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:64)
03-08 16:23:05.186 29448-29448/com.floatingmuseum.androidtest W/System.err:     at io.reactivex.internal.operators.observable.ObservableDoOnEach$DoOnEachObserver.onNext(ObservableDoOnEach.java:103)
03-08 16:23:05.186 29448-29448/com.floatingmuseum.androidtest W/System.err:     at com.jakewharton.retrofit2.adapter.rxjava2.CallObservable.subscribeActual(CallObservable.java:43)
03-08 16:23:05.186 29448-29448/com.floatingmuseum.androidtest W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:10700)
03-08 16:23:05.186 29448-29448/com.floatingmuseum.androidtest W/System.err:     at io.reactivex.internal.operators.observable.ObservableDoOnEach.subscribeActual(ObservableDoOnEach.java:42)
03-08 16:23:05.186 29448-29448/com.floatingmuseum.androidtest W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:10700)
03-08 16:23:05.186 29448-29448/com.floatingmuseum.androidtest W/System.err:     at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:33)
03-08 16:23:05.186 29448-29448/com.floatingmuseum.androidtest W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:10700)
03-08 16:23:05.186 29448-29448/com.floatingmuseum.androidtest W/System.err:     at io.reactivex.internal.operators.observable.ObservableRetryBiPredicate$RetryBiObserver.subscribeNext(ObservableRetryBiPredicate.java:100)
03-08 16:23:05.186 29448-29448/com.floatingmuseum.androidtest W/System.err:     at io.reactivex.internal.operators.observable.ObservableRetryBiPredicate.subscribeActual(ObservableRetryBiPredicate.java:39)
03-08 16:23:05.186 29448-29448/com.floatingmuseum.androidtest W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:10700)
03-08 16:23:05.186 29448-29448/com.floatingmuseum.androidtest W/System.err:     at io.reactivex.internal.operators.observable.ObservableScalarXMap$ScalarXMapObservable.subscribeActual(ObservableScalarXMap.java:166)
03-08 16:23:05.186 29448-29448/com.floatingmuseum.androidtest W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:10700)
03-08 16:23:05.186 29448-29448/com.floatingmuseum.androidtest W/System.err:     at io.reactivex.internal.operators.observable.ObservableFlatMap.subscribeActual(ObservableFlatMap.java:55)
03-08 16:23:05.186 29448-29448/com.floatingmuseum.androidtest W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:10700)
03-08 16:23:05.186 29448-29448/com.floatingmuseum.androidtest W/System.err:     at io.reactivex.internal.operators.observable.ObservableDoOnEach.subscribeActual(ObservableDoOnEach.java:42)
03-08 16:23:05.186 29448-29448/com.floatingmuseum.androidtest W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:10700)
03-08 16:23:05.186 29448-29448/com.floatingmuseum.androidtest W/System.err:     at io.reactivex.internal.operators.observable.ObservableFlatMap.subscribeActual(ObservableFlatMap.java:55)
03-08 16:23:05.186 29448-29448/com.floatingmuseum.androidtest W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:10700)
03-08 16:23:05.186 29448-29448/com.floatingmuseum.androidtest W/System.err:     at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.subscribeInner(ObservableFlatMap.java:162)
03-08 16:23:05.186 29448-29448/com.floatingmuseum.androidtest W/System.err:     at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.onNext(ObservableFlatMap.java:139)
03-08 16:23:05.186 29448-29448/com.floatingmuseum.androidtest W/System.err:     at io.reactivex.internal.observers.DisposableLambdaObserver.onNext(DisposableLambdaObserver.java:59)
03-08 16:23:05.186 29448-29448/com.floatingmuseum.androidtest W/System.err:     at io.reactivex.internal.operators.observable.ObservableScalarXMap$ScalarDisposable.run(ObservableScalarXMap.java:248)
03-08 16:23:05.186 29448-29448/com.floatingmuseum.androidtest W/System.err:     at io.reactivex.internal.operators.observable.ObservableJust.subscribeActual(ObservableJust.java:35)
03-08 16:23:05.186 29448-29448/com.floatingmuseum.androidtest W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:10700)
03-08 16:23:05.186 29448-29448/com.floatingmuseum.androidtest W/System.err:     at io.reactivex.internal.operators.observable.ObservableDoOnLifecycle.subscribeActual(ObservableDoOnLifecycle.java:33)
03-08 16:23:05.186 29448-29448/com.floatingmuseum.androidtest W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:10700)
03-08 16:23:05.186 29448-29448/com.floatingmuseum.androidtest W/System.err:     at io.reactivex.internal.operators.observable.ObservableFlatMap.subscribeActual(ObservableFlatMap.java:55)
03-08 16:23:05.186 29448-29448/com.floatingmuseum.androidtest W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:10700)
03-08 16:23:05.186 29448-29448/com.floatingmuseum.androidtest W/System.err:     at io.reactivex.internal.operators.observable.ObservableFlatMap.subscribeActual(ObservableFlatMap.java:55)
03-08 16:23:05.186 29448-29448/com.floatingmuseum.androidtest W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:10700)
03-08 16:23:05.186 29448-29448/com.floatingmuseum.androidtest W/System.err:     at io.reactivex.internal.operators.observable.ObservableDoOnEach.subscribeActual(ObservableDoOnEach.java:42)
03-08 16:23:05.186 29448-29448/com.floatingmuseum.androidtest W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:10700)
03-08 16:23:05.186 29448-29448/com.floatingmuseum.androidtest W/System.err:     at io.reactivex.internal.operators.observable.ObservableDoFinally.subscribeActual(ObservableDoFinally.java:45)
03-08 16:23:05.187 29448-29448/com.floatingmuseum.androidtest W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:10700)
03-08 16:23:05.187 29448-29448/com.floatingmuseum.androidtest W/System.err:     at io.reactivex.internal.operators.observable.ObservableSubscribeOn$1.run(ObservableSubscribeOn.java:39)
03-08 16:23:05.187 29448-29448/com.floatingmuseum.androidtest W/System.err:     at io.reactivex.Scheduler$1.run(Scheduler.java:138)
03-08 16:23:05.187 29448-29448/com.floatingmuseum.androidtest W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:59)
03-08 16:23:05.187 29448-29448/com.floatingmuseum.androidtest W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:51)
03-08 16:23:05.187 29448-29448/com.floatingmuseum.androidtest W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
03-08 16:23:05.187 29448-29448/com.floatingmuseum.androidtest W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
03-08 16:23:05.187 29448-29448/com.floatingmuseum.androidtest W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
03-08 16:23:05.187 29448-29448/com.floatingmuseum.androidtest W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
03-08 16:23:05.187 29448-29448/com.floatingmuseum.androidtest W/System.err:     at java.lang.Thread.run(Thread.java:776)
03-08 16:23:05.187 29448-29448/com.floatingmuseum.androidtest W/System.err: Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
03-08 16:23:05.187 29448-29448/com.floatingmuseum.androidtest W/System.err:     at libcore.io.Posix.open(Native Method)
03-08 16:23:05.187 29448-29448/com.floatingmuseum.androidtest W/System.err:     at libcore.io.BlockGuardOs.open(BlockGuardOs.java:187)
03-08 16:23:05.187 29448-29448/com.floatingmuseum.androidtest W/System.err:     at libcore.io.IoBridge.open(IoBridge.java:441)
03-08 16:23:05.187 29448-29448/com.floatingmuseum.androidtest W/System.err: 	... 81 more
```

I found there no .cache dir in Download directory

**Comment by floatingmuseum** [comment]
Android version 7.0

**Comment by ssseasonnn** [comment]
华为手机设置下载路径的方式好像不一样，不能用Environment.getExternalStorageDirectory来获取，你找找如何获取路径的方法然后设置成默认的下载路径即可

**Comment by floatingmuseum** [comment]
i found the reason,cause there is no permission request,so without write permission，this happended，my bad。
but there sitll has some thing wrong with download percent，i download an apk with 5 threads，sometimes the percent like jump from 70 to 90,and then it jump back to 70.

**Comment by ssseasonnn** [comment]
Ok , got it, I'll fix this as fast as I can.
