### ISSUE TITLE
同一个文件存在的时候，重复下载出错

### ISSUE THREAD

**Issue by Sabirjan** [ssseasonnn/RxDownload#7]
java.lang.RuntimeException: unknown error
                                                           at zlc.season.rxdownload.RxDownload$16.call(RxDownload.java:510)
                                                           at zlc.season.rxdownload.RxDownload$16.call(RxDownload.java:502)
                                                           at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69)
                                                           at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$RequestArbiter.request(RxJavaCallAdapterFactory.java:173)
                                                           at rx.internal.producers.ProducerArbiter.setProducer(ProducerArbiter.java:126)
                                                           at rx.internal.operators.OperatorRetryWithPredicate$SourceSubscriber$1$1.setProducer(OperatorRetryWithPredicate.java:122)
                                                           at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102)
                                                           at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:152)
                                                           at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:138)
                                                           at rx.Observable.unsafeSubscribe(Observable.java:10151)
                                                           at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
                                                           at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
                                                           at rx.Observable.unsafeSubscribe(Observable.java:10151)
                                                           at rx.internal.operators.OperatorRetryWithPredicate$SourceSubscriber$1.call(OperatorRetryWithPredicate.java:127)
                                                           at rx.internal.schedulers.TrampolineScheduler$InnerCurrentThreadScheduler.enqueue(TrampolineScheduler.java:73)
                                                           at rx.internal.schedulers.TrampolineScheduler$InnerCurrentThreadScheduler.schedule(TrampolineScheduler.java:52)
                                                           at rx.internal.operators.OperatorRetryWithPredicate$SourceSubscriber.onNext(OperatorRetryWithPredicate.java:79)
                                                           at rx.internal.operators.OperatorRetryWithPredicate$SourceSubscriber.onNext(OperatorRetryWithPredicate.java:45)
                                                           at rx.internal.util.ScalarSynchronousObservable$WeakSingleProducer.request(ScalarSynchronousObservable.java:276)
                                                           at rx.Subscriber.setProducer(Subscriber.java:209)
                                                           at rx.internal.util.ScalarSynchronousObservable$JustOnSubscribe.call(ScalarSynchronousObservable.java:138)
                                                           at rx.internal.util.ScalarSynchronousObservable$JustOnSubscribe.call(ScalarSynchronousObservable.java:129)
                                                           at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
                                                           at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
                                                           at rx.Observable.unsafeSubscribe(Observable.java:10151)
                                                           at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
                                                           at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
                                                           at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
                                                           at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
                                                           at rx.Observable.unsafeSubscribe(Observable.java:10151)
                                                           at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
                                                           at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
                                                           at rx.Observable.unsafeSubscribe(Observable.java:10151)
                                                           at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
                                                           at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
                                                           at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
                                                           at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
                                                           at rx.Observable.unsafeSubscribe(Observable.java:10151)
                                                           at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
                                                           at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:228)
                                                           at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
                                                           at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                           at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                           at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
                                                           at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                           at java.lang.Thread.run(Thread.java:841)
                                                        Caused by: rx.excepti

![image](https://cloud.githubusercontent.com/assets/7404699/21140945/82325a22-c175-11e6-9c5e-966464a89e0a.png)

**Comment by ssseasonnn** [comment]
这是因为你服务端返回的响应码不对，你看看是不是404

**Comment by Sabirjan** [comment]
我怎么看？
![image](https://cloud.githubusercontent.com/assets/7404699/21141123/791227b4-c176-11e6-8e32-3300e77f497d.png)

**Comment by ssseasonnn** [comment]
抓个包啊

**Comment by Sabirjan** [comment]
![image](https://cloud.githubusercontent.com/assets/7404699/21148001/c85fdb52-c191-11e6-86f7-a8df8c167058.png)
 416

**Comment by Sabirjan** [comment]
我现在下载的是mp3文件

**Comment by Sabirjan** [comment]
HEAD http://cdn.apandim.com//mp3/uyghur/sazim/kizimga-hat.mp3 HTTP/1.1
Range: bytes=0-
If-Range: Sat, 26 Nov 2016 10:05:21 GMT+00:00
Host: cdn.apandim.com
Connection: Keep-Alive
Accept-Encoding: gzip
User-Agent: okhttp/3.4.1

**Comment by Sabirjan** [comment]
能不能修改user agent

**Comment by ssseasonnn** [comment]
![qq 20161214091525](https://cloud.githubusercontent.com/assets/10646230/21166131/8cd0ce46-c1de-11e6-929c-5e82e1478d3a.png)

检查一下你的服务器, 为什么返回的是这个值

**Comment by ssseasonnn** [comment]
![qq 20161214091642](https://cloud.githubusercontent.com/assets/10646230/21166161/bd94700a-c1de-11e6-8c74-97da3e8fd156.png)

正常情况下, 当我请求头加上Range字段的时候, 服务器返回的应该是这样的

**Comment by ssseasonnn** [comment]
user-agent是OKHTTP设置的, 若你需要更改可以自己定义Retrofit客户端, 然后传给RxDownload使用就行了

**Comment by Sabirjan** [comment]
没有解决办法吗？

**Comment by ssseasonnn** [comment]
你是只要下载就行是吗？还是必须得断点下载？

**Comment by Sabirjan** [comment]
下载就可以了

**Comment by ssseasonnn** [comment]
那我这边给你处理一下，下午发个新版本，你注意一下

**Comment by Sabirjan** [comment]
好的！非常感谢！

**Comment by ssseasonnn** [comment]
@Sabirjan 新版本已发, 版本号1.2.7,  RxJava2分支正在修改中, 稍后发.

**Comment by ssseasonnn** [comment]
@Sabirjan RxJava2分支也发布了, 版本号1.0.5
