### ISSUE TITLE
服务端开启GZip压缩文件，下载会出现 RxDownload: java.lang.IllegalArgumentException: newLength < 0 异常

### ISSUE THREAD

**Issue by AifeiI** [ssseasonnn/RxDownload#73]
从 1.1.1 更新至 2.0.2 版本后，就出现这个问题，我调试一番后，确认是因为开启 GZip 后，HTTP Response 中的 Header 不包含 Content-Length 导致的。

我暂时只能将需要使用 RxDownload 进行下载的文件，从 GZip 压缩名单内排除才能继续使用 RxDownload

异常信息
---

```java
java.lang.IllegalArgumentException: newLength < 0
    at java.io.RandomAccessFile.setLength(RandomAccessFile.java:586)
    at zlc.season.rxdownload2.function.FileHelper.prepareFile(FileHelper.java:244)
    at zlc.season.rxdownload2.function.FileHelper.prepareDownload(FileHelper.java:108)
    at zlc.season.rxdownload2.entity.TemporaryRecord.prepareRangeDownload(TemporaryRecord.java:113)
    at zlc.season.rxdownload2.entity.DownloadType$MultiThreadDownload.prepareDownload(DownloadType.java:297)
    at zlc.season.rxdownload2.function.DownloadHelper.download(DownloadHelper.java:137)
    at zlc.season.rxdownload2.function.DownloadHelper.access$200(DownloadHelper.java:46)
    at zlc.season.rxdownload2.function.DownloadHelper$3.apply(DownloadHelper.java:118)
    at zlc.season.rxdownload2.function.DownloadHelper$3.apply(DownloadHelper.java:115)
	...
```

**Comment by AifeiI** [comment]
@ssseasonnn Retrofit2 默认是开启Gzip的（Header: Accept-Encoding: gzip）

**Comment by cc2hh** [comment]
我也遇到这个问题了，估计只有自己去源码里面查找原因，修改了，不然以判断Gzip太死板了，并且很多下载并不由我们移动端能决定的啊

**Comment by vivek-wo** [comment]
@cc2hh @AifeiI 我也遇到这个问题，请教下，不知道两位是怎么解决的？

**Comment by AifeiI** [comment]
@vivek-wo 自己重载RxDownload2 的 Retrofit，然后按自己需求去修改 Header，例如不添加 Gzip 。

**Comment by vivek-wo** [comment]
@AifeiI 好的，谢谢！
