### ISSUE TITLE
下载失败时，提示Context is NULL! You should call #RxDownload.context(Context context)# 

### ISSUE THREAD

**Issue by henryloveself** [ssseasonnn/RxDownload#8]
12-14 20:17:01.031 14896-15081/com.star.app.tvhelper.ui.shanxi W/RxDownload: java.lang.IllegalStateException: Context is NULL! You should call #RxDownload.context(Context context)# first!
                                                                                 at zlc.season.rxdownload.RxDownload$11.call(RxDownload.java:430)
                                                                                 at rx.internal.util.ActionObserver.onCompleted(ActionObserver.java:49)
                                                                                 at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onCompleted(OnSubscribeDoOnEach.java:63)
                                                                                 at rx.internal.operators.OperatorMerge$MergeSubscriber.emitLoop(OperatorMerge.java:656)
                                                                                 at rx.internal.operators.OperatorMerge$MergeSubscriber.emit(OperatorMerge.java:568)
                                                                                 at rx.internal.operators.OperatorMerge$MergeProducer.request(OperatorMerge.java:133)
                                                                                 at rx.internal.operators.OperatorSubscribeOn$1$1$1$1.call(OperatorSubscribeOn.java:85)
                                                                                 at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:228)
                                                                                 at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
                                                                                 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                                                 at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
                                                                                 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
                                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1115)
                                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:590)
                                                                                 at java.lang.Thread.run(Thread.java:818)

**Comment by ssseasonnn** [comment]
@henryloveself 哥，不是已经提示你了吗，需要传context啊！你都不看异常信息吗？

**Comment by henryloveself** [comment]
恩恩 灰常感谢，不过我觉得你这点应该还是要在在使用文档中特别说明下，下载完成需要自动安装功能的时候，必须要传递Context对象

**Comment by ssseasonnn** [comment]
哥，文档里写了的，你再仔细看看呢

**Comment by ssseasonnn** [comment]
问题已解决, 我关闭了
