### ISSUE TITLE
使用master分支最新代码下载时，经常会中断，报这个错误io.reactivex.exceptions.MissingBackpressureException

### ISSUE THREAD

**Issue by l7356507** [ssseasonnn/RxDownload#82]
io.reactivex.exceptions.MissingBackpressureException: Could not deliver value due to lack of requests
at io.reactivex.internal.operators.flowable.FlowableThrottleFirstTimed$DebounceTimedSubscriber.onNext(FlowableThrottleFirstTimed.java:99)
                                                                at io.reactivex.internal.util.NotificationLite.accept(NotificationLite.java:224)
                                                                at io.reactivex.internal.operators.flowable.FlowableReplay$BoundedReplayBuffer.replay(FlowableReplay.java:961)
                                                                at io.reactivex.internal.operators.flowable.FlowableReplay$ReplaySubscriber.onNext(FlowableReplay.java:493)
                                                                at io.reactivex.internal.operators.flowable.FlowableCreate$LatestAsyncEmitter.drain(FlowableCreate.java:662)
                                                                at io.reactivex.internal.operators.flowable.FlowableCreate$LatestAsyncEmitter.onNext(FlowableCreate.java:588)
                                                                at zlc.season.rxdownload2.function.FileHelper.saveFile(FileHelper.java:154)
                                                                at zlc.season.rxdownload2.entity.TemporaryRecord.save(TemporaryRecord.java:147)
                                                                at zlc.season.rxdownload2.entity.DownloadType$ContinueDownload$2.subscribe(DownloadType.java:292)
                                                                at io.reactivex.internal.operators.flowable.FlowableCreate.subscribeActual(FlowableCreate.java:72)
                                                                at io.reactivex.Flowable.subscribe(Flowable.java:12970)
                                                                at io.reactivex.internal.operators.flowable.FlowableReplay.connect(FlowableReplay.java:334)
                                                                at io.reactivex.internal.operators.flowable.FlowableAutoConnect.subscribeActual(FlowableAutoConnect.java:50)
                                                                at io.reactivex.Flowable.subscribe(Flowable.java:12970)
                                                                at io.reactivex.internal.operators.flowable.FlowableThrottleFirstTimed.subscribeActual(FlowableThrottleFirstTimed.java:45)
                                                                at io.reactivex.Flowable.subscribe(Flowable.java:12970)
                                                                at io.reactivex.Flowable.subscribe(Flowable.java:12917)
                                                                at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.onNext(FlowableFlatMap.java:163)
                                                                at io.reactivex.internal.operators.flowable.FlowableFromArray$ArraySubscription.slowPath(FlowableFromArray.java:164)
                                                                at io.reactivex.internal.operators.flowable.FlowableFromArray$BaseArraySubscription.request(FlowableFromArray.java:89)
                                                                at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.onSubscribe(FlowableFlatMap.java:117)
                                                                at io.reactivex.internal.operators.flowable.FlowableFromArray.subscribeActual(FlowableFromArray.java:37)
                                                                at io.reactivex.Flowable.subscribe(Flowable.java:12970)
                                                                at io.reactivex.internal.operators.flowable.FlowableFlatMap.subscribeActual(FlowableFlatMap.java:53)
                                                                at io.reactivex.Flowable.subscribe(Flowable.java:12970)
                                                                at io.reactivex.Flowable.subscribe(Flowable.java:12917)
                                                                at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82)
                                                                at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:59)
                                                                at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:51)
                                                                at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
                                                                at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                at java.lang.Thread.run(Thread.java:841)

**Comment by bappleug** [comment]
可以给个复现问题的配置和下载源么？我好查一下
